"use client";

import { useState } from "react";

const DAYS = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];

type Offering = { id:string; name:string; description?:string|null; duration_minutes:number; price:number; currency:string; status:string; requires_confirmation:boolean };
type Staff = { id:string; display_name:string; bio?:string|null; status:string };
type Appointment = { id:string; public_id:string; customer_name:string; starts_at:string; ends_at:string; status:string; price:number; currency:string; service_offerings?:{name:string}|null; service_staff?:{display_name:string}|null };

export default function ProviderWorkspace({ business, profile, categories, offerings, staff, appointments }:{business:any;profile:any;categories:any[];offerings:Offering[];staff:Staff[];appointments:Appointment[]}) {
  const [tab,setTab]=useState("overview");
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState("");
  const [service,setService]=useState({name:"",description:"",durationMinutes:"60",price:"",currency:"KES"});
  const [person,setPerson]=useState({displayName:"",bio:""});
  const [schedule,setSchedule]=useState({staffId:staff[0]?.id||"",dayOfWeek:"1",startTime:"09:00",endTime:"17:00"});

  async function act(payload:any) {
    setBusy(true); setMessage("");
    try { const r=await fetch("/api/business/services/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,serviceProfileId:profile?.id})}); const j=await r.json(); if(!r.ok) throw new Error(j.error||"Something went wrong"); setMessage("Saved. Refreshing your workspace…"); window.location.reload(); }
    catch(e){setMessage(e instanceof Error?e.message:"Unable to save");} finally{setBusy(false);}
  }

  if(!profile) return <Setup business={business} categories={categories} busy={busy} onAction={act} />;

  return <div className="grid gap-8 lg:grid-cols-[220px_1fr]">
    <aside className="lg:sticky lg:top-6 lg:self-start"><nav className="rounded-[1.75rem] bg-white p-2 shadow-[0_20px_70px_-55px_rgba(0,0,0,.5)]">
      {[['overview','Overview'],['services','Services'],['team','Team'],['hours','Working hours'],['appointments','Appointments']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`w-full rounded-2xl px-4 py-3 text-left text-sm font-semibold transition ${tab===id?'bg-black text-white':'text-black/55 hover:bg-black/[.04]'}`}>{label}</button>)}
    </nav><div className="mt-4 rounded-[1.5rem] bg-black p-5 text-white"><p className="text-[10px] uppercase tracking-[.2em] text-white/40">Booking</p><p className="mt-2 text-xl font-semibold">{profile.booking_status==='open'?'Open':'Closed'}</p><button disabled={busy} onClick={()=>act({action:'toggle_booking',open:profile.booking_status!=='open'})} className="mt-4 w-full rounded-xl bg-white/10 px-3 py-2 text-xs font-semibold hover:bg-white/15">{profile.booking_status==='open'?'Pause bookings':'Open bookings'}</button></div></aside>

    <section className="min-w-0">
      {message&&<div className="mb-5 rounded-2xl bg-black px-4 py-3 text-sm font-medium text-white">{message}</div>}
      {tab==='overview'&&<Overview business={business} profile={profile} offerings={offerings} staff={staff} appointments={appointments}/>} 
      {tab==='services'&&<section className="rounded-[2rem] bg-white p-7"><Header eyebrow="Service menu" title="What customers can book"/><div className="mt-7 grid gap-3 sm:grid-cols-2">{offerings.map(o=><div key={o.id} className="rounded-2xl border border-black/8 p-5"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{o.name}</h3><p className="mt-1 text-xs text-black/45">{o.duration_minutes} min · {o.status}</p></div><p className="font-semibold">{o.currency} {Number(o.price).toLocaleString()}</p></div></div>)}{!offerings.length&&<Empty text="No services yet. Add your first bookable service below."/>}</div><div className="mt-8 rounded-2xl bg-[#f7f7f4] p-5"><h3 className="font-semibold">Add a service</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={service.name} onChange={e=>setService({...service,name:e.target.value})} placeholder="Service name" className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"/><input value={service.price} onChange={e=>setService({...service,price:e.target.value})} placeholder="Price" type="number" min="0" className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"/><input value={service.durationMinutes} onChange={e=>setService({...service,durationMinutes:e.target.value})} placeholder="Duration (minutes)" type="number" min="5" className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"/><input value={service.currency} onChange={e=>setService({...service,currency:e.target.value.toUpperCase()})} placeholder="Currency" className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"/><textarea value={service.description} onChange={e=>setService({...service,description:e.target.value})} placeholder="Short description" className="min-h-24 rounded-xl border border-black/10 bg-white px-4 py-3 text-sm sm:col-span-2"/></div><button disabled={busy||!service.name} onClick={()=>act({action:'create_offering',...service,durationMinutes:Number(service.durationMinutes),price:Number(service.price||0)})} className="mt-4 rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Add service</button></div></section>}
      {tab==='team'&&<section className="rounded-[2rem] bg-white p-7"><Header eyebrow="Your team" title="Specialists customers can book"/><div className="mt-7 space-y-3">{staff.map(s=><div key={s.id} className="flex items-center justify-between rounded-2xl border border-black/8 p-4"><div><p className="font-semibold">{s.display_name}</p><p className="text-xs text-black/45">{s.status}</p></div><div className="rounded-full bg-black/[.04] px-3 py-1 text-[10px] font-semibold uppercase tracking-wider">Team member</div></div>)}{!staff.length&&<Empty text="Add your first specialist below."/>}</div><div className="mt-8 rounded-2xl bg-[#f7f7f4] p-5"><h3 className="font-semibold">Add team member</h3><div className="mt-4 grid gap-3"><input value={person.displayName} onChange={e=>setPerson({...person,displayName:e.target.value})} placeholder="Full name" className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"/><textarea value={person.bio} onChange={e=>setPerson({...person,bio:e.target.value})} placeholder="Short bio (optional)" className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"/></div><button disabled={busy||!person.displayName} onClick={()=>act({action:'create_staff',displayName:person.displayName,bio:person.bio})} className="mt-4 rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Add team member</button></div></section>}
      {tab==='hours'&&<section className="rounded-[2rem] bg-white p-7"><Header eyebrow="Availability" title="Working hours"/><p className="mt-2 max-w-xl text-sm leading-6 text-black/50">Set recurring hours for each specialist. SafariPlug only offers customers slots that fall inside these hours and remain free of blockouts and appointments.</p><div className="mt-7 rounded-2xl bg-[#f7f7f4] p-5"><div className="grid gap-3 sm:grid-cols-4"><select value={schedule.staffId} onChange={e=>setSchedule({...schedule,staffId:e.target.value})} className="rounded-xl border border-black/10 bg-white px-3 py-3 text-sm">{staff.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select><select value={schedule.dayOfWeek} onChange={e=>setSchedule({...schedule,dayOfWeek:e.target.value})} className="rounded-xl border border-black/10 bg-white px-3 py-3 text-sm">{DAYS.map((d,i)=><option key={d} value={i}>{d}</option>)}</select><input type="time" value={schedule.startTime} onChange={e=>setSchedule({...schedule,startTime:e.target.value})} className="rounded-xl border border-black/10 bg-white px-3 py-3 text-sm"/><input type="time" value={schedule.endTime} onChange={e=>setSchedule({...schedule,endTime:e.target.value})} className="rounded-xl border border-black/10 bg-white px-3 py-3 text-sm"/></div><button disabled={busy||!schedule.staffId} onClick={()=>act({action:'set_availability',...schedule,dayOfWeek:Number(schedule.dayOfWeek)})} className="mt-4 rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Save working hours</button></div></section>}
      {tab==='appointments'&&<section className="rounded-[2rem] bg-white p-7"><Header eyebrow="Calendar" title="Customer appointments"/><div className="mt-7 divide-y divide-black/7">{appointments.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="font-semibold">{a.customer_name}</p><p className="mt-1 text-xs text-black/45">{new Date(a.starts_at).toLocaleString()} · {a.service_offerings?.name||'Service'} · {a.service_staff?.display_name||'Team'}</p></div><div className="flex items-center gap-3"><span className="text-sm font-semibold">{a.currency} {Number(a.price).toLocaleString()}</span>{['pending','confirmed'].includes(a.status)&&<button disabled={busy} onClick={()=>act({action:'appointment_status',appointmentId:a.id,status:a.status==='pending'?'confirmed':'completed'})} className="rounded-xl bg-black px-3 py-2 text-[11px] font-semibold text-white">{a.status==='pending'?'Confirm':'Complete'}</button>}</div></div>)}{!appointments.length&&<Empty text="Your appointment calendar is clear."/>}</div></section>}
    </section>
  </div>;
}

function Setup({business,categories,busy,onAction}:{business:any;categories:any[];busy:boolean;onAction:(p:any)=>void}) { const [cat,setCat]=useState(categories[0]?.slug||""); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); if(!business)return <section className="rounded-[2rem] bg-white p-8"><Header eyebrow="Partner setup" title="Create your service business"/><p className="mt-3 max-w-xl text-sm leading-6 text-black/50">Start with your business details. You can then add services, specialists and working hours.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Business name" className="rounded-xl border border-black/10 px-4 py-3 text-sm"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone / WhatsApp" className="rounded-xl border border-black/10 px-4 py-3 text-sm"/></div><button disabled={busy||!name||!phone} onClick={()=>onAction({action:'create_business',name,phone,businessType:'Service Provider'})} className="mt-4 rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Create business</button></section>; return <section className="rounded-[2rem] bg-white p-8"><Header eyebrow="Partner setup" title="Choose your service category"/><p className="mt-3 max-w-xl text-sm leading-6 text-black/50">This determines how SafariPlug presents your business in discovery and Concierge.</p><select value={cat} onChange={e=>setCat(e.target.value)} className="mt-7 w-full max-w-xl rounded-xl border border-black/10 px-4 py-3 text-sm">{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><button disabled={busy||!cat} onClick={()=>onAction({action:'create_profile',businessId:business.id,categorySlug:cat})} className="mt-4 rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Create service workspace</button></section> }
function Overview({business,profile,offerings,staff,appointments}:{business:any;profile:any;offerings:Offering[];staff:Staff[];appointments:Appointment[]}) { const upcoming=appointments.filter(a=>new Date(a.starts_at)>=new Date()); return <div className="space-y-6"><div className="rounded-[2rem] bg-black p-8 text-white"><p className="text-[10px] uppercase tracking-[.25em] text-white/40">Partner workspace</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">{business.name}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">Your storefront, services, specialists and calendar live here. Customers only see bookable services when your calendar is open.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Services" value={offerings.length}/><Metric label="Team" value={staff.length}/><Metric label="Upcoming" value={upcoming.length}/><Metric label="Bookings" value={profile.booking_status==='open'?'Open':'Closed'}/></div></div> }
function Header({eyebrow,title}:{eyebrow:string;title:string}){return <><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-black/40">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{title}</h2></>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-[1.5rem] bg-white p-5 shadow-[0_15px_50px_-45px_rgba(0,0,0,.5)]"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-black/40">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-black/10 py-12 text-center text-sm text-black/45">{text}</div>}
