"use client";

import { useState } from "react";
import { getServiceTemplates, type ServiceTemplate } from "@/lib/service-catalog";

export default function ServiceQuickAdd({ serviceProfileId, categorySlug, existingNames=[] }:{serviceProfileId:string;categorySlug?:string|null;existingNames?:string[]}) {
  const templates=getServiceTemplates(categorySlug);
  const [busy,setBusy]=useState<string|null>(null);
  const [message,setMessage]=useState("");
  const [selected,setSelected]=useState<ServiceTemplate|null>(null);
  if(!templates.length)return null;
  async function add(template:ServiceTemplate){
    setBusy(template.name); setMessage("");
    try { const r=await fetch("/api/business/services/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create_offering",serviceProfileId,...template,durationMinutes:template.durationMinutes,price:0,active:false})}); const j=await r.json(); if(!r.ok)throw new Error(j.error||"Unable to add service"); setMessage(`${template.name} added as a draft. Set its price before publishing.`); } catch(e){setMessage(e instanceof Error?e.message:"Unable to add service");} finally{setBusy(null);setSelected(null);} 
  }
  return <section className="mt-8 rounded-[2rem] border border-black/8 bg-black p-6 text-white"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-white/40">Recommended for your category</p><h3 className="mt-2 text-xl font-semibold">Start with a proven service</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-white/55">Add a recommended service as a draft, then set your actual price and publish it. SafariPlug never assumes that you offer a service just because it is recommended.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{templates.map(t=>{const exists=existingNames.some(n=>n.toLowerCase()===t.name.toLowerCase());return <button key={t.name} disabled={Boolean(busy)||exists} onClick={()=>setSelected(t)} className="rounded-2xl border border-white/10 bg-white/[.06] p-4 text-left transition hover:bg-white/[.1] disabled:opacity-45"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{t.name}</p><p className="mt-1 text-xs leading-5 text-white/45">{t.durationMinutes} min · draft</p></div><span className="text-white/40">{exists?"✓":"+"}</span></div></button>})}</div>{message&&<p className="mt-4 text-sm text-white/70">{message}</p>}{selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-5" onClick={()=>setSelected(null)}><div className="w-full max-w-lg rounded-[2rem] bg-white p-7 text-black" onClick={e=>e.stopPropagation()}><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-black/40">Add draft service</p><h3 className="mt-2 text-2xl font-semibold">{selected.name}</h3><p className="mt-3 text-sm leading-6 text-black/55">{selected.description}</p><div className="mt-5 rounded-2xl bg-[#f7f7f4] p-4 text-sm"><strong>{selected.durationMinutes} minutes</strong><p className="mt-1 text-xs text-black/45">Price starts at KES 0 as a draft. You must set your actual customer price before publishing.</p></div><div className="mt-5 flex gap-2"><button onClick={()=>setSelected(null)} className="rounded-xl border border-black/10 px-4 py-3 text-sm font-semibold">Cancel</button><button disabled={Boolean(busy)} onClick={()=>add(selected)} className="rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white">{busy?"Adding…":"Add draft"}</button></div></div></div>}</section>;
}
