"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Category = { id: string; name: string; description?: string | null; sort_order: number; active: boolean };
type OptionValue = { id: string; name: string; price_delta: number; sort_order: number; active?: boolean };
type Option = { id: string; name: string; required: boolean; sort_order: number; active?: boolean; restaurant_menu_item_option_values?: OptionValue[] };
type Item = { id: string; category_id?: string | null; name: string; description?: string | null; price: number; currency: string; preparation_time_minutes?: number | null; available: boolean; active: boolean; restaurant_menu_item_options?: Option[] };
type Settings = { ordering_enabled: boolean; pickup_enabled: boolean; safari_driver_enabled: boolean; customer_driver_enabled: boolean; restaurant_delivery_enabled: boolean; minimum_order_amount: number; restaurant_delivery_fee: number; free_delivery_threshold: number; safari_driver_base_fee: number; safari_driver_per_km: number; customer_driver_base_fee: number; customer_driver_per_km: number; preparation_time_minutes: number };
const defaults: Settings = { ordering_enabled:true,pickup_enabled:true,safari_driver_enabled:true,customer_driver_enabled:false,restaurant_delivery_enabled:false,minimum_order_amount:0,restaurant_delivery_fee:0,free_delivery_threshold:0,safari_driver_base_fee:0,safari_driver_per_km:0,customer_driver_base_fee:0,customer_driver_per_km:0,preparation_time_minutes:30 };
const emptyItem={name:"",description:"",price:"",categoryId:"",preparationTimeMinutes:""};

export default function RestaurantSupplierPage(){
 const [businessId,setBusinessId]=useState(""); const [categories,setCategories]=useState<Category[]>([]); const [items,setItems]=useState<Item[]>([]); const [settings,setSettings]=useState<Settings>(defaults); const [categoryName,setCategoryName]=useState(""); const [item,setItem]=useState(emptyItem); const [editingId,setEditingId]=useState(""); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
 async function load(){const o=await fetch("/api/supplier/onboarding",{cache:"no-store"});if(!o.ok)return setMessage("Please sign in through your supplier invitation first.");const s=await o.json();const id=s.business?.id;if(!id||s.business?.business_type!=="Restaurant")return setMessage("This menu workspace is available to restaurant suppliers only.");setBusinessId(id);const r=await fetch(`/api/restaurants/menu?businessId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)return setMessage(d.error||"Unable to load your restaurant menu.");setCategories(d.categories||[]);setItems(d.items||[]);setSettings({...defaults,...(d.settings||{})});}
 useEffect(()=>{void load()},[]);
 async function request(method:"POST"|"PATCH",body:Record<string,unknown>){setSaving(true);setMessage("");try{const r=await fetch("/api/restaurants/menu",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMessage(d.error||"Unable to save.");return false}await load();setMessage("Saved.");return true}finally{setSaving(false)}}
 async function addCategory(){const name=categoryName.trim();if(!name)return; if(await request("POST",{action:"category",name,description:"",sortOrder:categories.length}))setCategoryName("");}
 async function saveItem(){if(!item.name.trim()||item.price==="")return setMessage("Enter a menu item name and price.");const body={name:item.name.trim(),description:item.description,price:Number(item.price),currency:"KES",categoryId:item.categoryId||null,preparationTimeMinutes:item.preparationTimeMinutes?Number(item.preparationTimeMinutes):null};const ok=editingId?await request("PATCH",{type:"item",id:editingId,...body}):await request("POST",{action:"item",...body,sortOrder:items.length});if(ok){setItem(emptyItem);setEditingId("")}}
 function editItem(entry:Item){setEditingId(entry.id);setItem({name:entry.name,description:entry.description||"",price:String(entry.price),categoryId:entry.category_id||"",preparationTimeMinutes:entry.preparation_time_minutes?String(entry.preparation_time_minutes):""});window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
 async function toggleItem(entry:Item){await request("PATCH",{type:"item",id:entry.id,active:!entry.active});}
 async function toggleAvailable(entry:Item){await request("PATCH",{type:"item",id:entry.id,available:!entry.available});}
 async function toggleCategory(entry:Category){await request("PATCH",{type:"category",id:entry.id,name:entry.name,description:entry.description||"",sortOrder:entry.sort_order,active:!entry.active});}
 async function saveSettings(){await request("POST",{action:"settings",settings});}
 if(!businessId)return <main className="mx-auto max-w-5xl px-6 py-16"><h1 className="text-3xl font-semibold">Restaurant menu & ordering</h1><p className="mt-3 text-black/60">{message||"Loading your restaurant workspace…"}</p></main>;
 const toggles:Array<[keyof Settings,string]>=[["ordering_enabled","Accept SafariPlug orders"],["pickup_enabled","Offer customer pickup"],["safari_driver_enabled","Offer SafariPlug driver delivery"],["customer_driver_enabled","Allow customer-arranged driver delivery"],["restaurant_delivery_enabled","Offer restaurant delivery"]];
 return <main className="mx-auto max-w-5xl px-6 py-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-[.2em] text-black/40">Restaurant supplier</p><h1 className="mt-2 text-4xl font-semibold">Menu & ordering</h1><p className="mt-2 text-black/60">Manage the live menu customers see, item availability, and ordering fulfillment.</p></div><div className="flex gap-2 text-sm"><Link href="/supplier/onboarding" className="rounded-full border border-black/15 px-4 py-2">Business profile</Link><Link href="/supplier/restaurant-orders" className="rounded-full bg-black px-4 py-2 text-white">Manage orders</Link></div></div>
 <section className="mt-8 rounded-2xl border border-black/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Ordering settings</h2><p className="mt-1 text-sm text-black/50">Control how customers can receive food.</p></div><span className={`rounded-full px-3 py-1 text-xs ${settings.ordering_enabled?"bg-green-500/10 text-green-700":"bg-black/5 text-black/50"}`}>{settings.ordering_enabled?"Ordering live":"Ordering paused"}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{toggles.map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-xl bg-black/[.03] p-3 text-sm"><input type="checkbox" checked={Boolean(settings[key])} onChange={e=>setSettings(s=>({...s,[key]:e.target.checked}))}/>{label}</label>)}{([["minimum_order_amount","Minimum order (KES)"],["restaurant_delivery_fee","Restaurant delivery fee (KES)"],["free_delivery_threshold","Free delivery above (KES)"],["preparation_time_minutes","Typical preparation time (minutes)"]] as const).map(([key,label])=><label key={key} className="text-sm"><span className="mb-1 block">{label}</span><input type="number" min={0} value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:Number(e.target.value)}))} className="w-full rounded-xl border border-black/15 px-3 py-2.5"/></label>)}</div><div className="mt-5 border-t border-black/10 pt-5"><h3 className="font-medium">Driver pricing</h3><div className="mt-3 grid gap-3 md:grid-cols-4">{([["safari_driver_base_fee","SafariPlug base (KES)"],["safari_driver_per_km","SafariPlug / km"],["customer_driver_base_fee","Customer driver base (KES)"],["customer_driver_per_km","Customer driver / km"]] as const).map(([key,label])=><label key={key} className="text-sm"><span className="mb-1 block">{label}</span><input type="number" min={0} value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:Number(e.target.value)}))} className="w-full rounded-xl border border-black/15 px-3 py-2.5"/></label>)}</div></div><button disabled={saving} onClick={()=>void saveSettings()} className="mt-5 rounded-full bg-black px-5 py-2.5 text-sm text-white disabled:opacity-40">Save ordering settings</button></section>
 <section className="mt-6 rounded-2xl border border-black/10 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Menu categories</h2><p className="mt-1 text-sm text-black/50">Deactivating a category keeps existing orders intact.</p></div></div><div className="mt-4 flex gap-2"><input value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="Breakfast, Main Courses, Drinks" className="min-w-0 flex-1 rounded-xl border border-black/15 px-3 py-2.5"/><button disabled={saving} onClick={()=>void addCategory()} className="rounded-full bg-black px-4 py-2.5 text-sm text-white">Add category</button></div><div className="mt-4 space-y-2">{categories.map(c=><div key={c.id} className="flex items-center justify-between gap-3 rounded-xl bg-black/[.04] px-4 py-3 text-sm"><span className={c.active?"":"line-through opacity-45"}>{c.name}</span><button onClick={()=>void toggleCategory(c)} className="rounded-full border border-black/10 px-3 py-1.5 text-xs">{c.active?"Deactivate":"Activate"}</button></div>)}</div></section>
 <section className="mt-6 rounded-2xl border border-black/10 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{editingId?"Edit menu item":"Add menu item"}</h2><p className="mt-1 text-sm text-black/50">Prices are stored in the restaurant currency currently configured as KES.</p></div>{editingId&&<button onClick={()=>{setEditingId("");setItem(emptyItem)}} className="text-sm underline">Cancel edit</button>}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><input placeholder="Item name" value={item.name} onChange={e=>setItem(v=>({...v,name:e.target.value}))} className="rounded-xl border border-black/15 px-3 py-2.5"/><input type="number" min="0" placeholder="Price in KES" value={item.price} onChange={e=>setItem(v=>({...v,price:e.target.value}))} className="rounded-xl border border-black/15 px-3 py-2.5"/><textarea placeholder="Description" value={item.description} onChange={e=>setItem(v=>({...v,description:e.target.value}))} rows={3} className="rounded-xl border border-black/15 px-3 py-2.5"/><div className="grid gap-3"><select value={item.categoryId} onChange={e=>setItem(v=>({...v,categoryId:e.target.value}))} className="rounded-xl border border-black/15 px-3 py-2.5"><option value="">No category</option>{categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="number" min="1" placeholder="Preparation time (minutes, optional)" value={item.preparationTimeMinutes} onChange={e=>setItem(v=>({...v,preparationTimeMinutes:e.target.value}))} className="rounded-xl border border-black/15 px-3 py-2.5"/></div></div><button disabled={saving} onClick={()=>void saveItem()} className="mt-4 rounded-full bg-black px-5 py-2.5 text-sm text-white disabled:opacity-40">{editingId?"Save item":"Add menu item"}</button></section>
 <section className="mt-6 rounded-2xl border border-black/10 p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Current menu</h2><p className="mt-1 text-sm text-black/50">Use availability for temporary stock changes; deactivate for items you no longer sell.</p></div><span className="text-sm text-black/50">{items.filter(i=>i.active).length} active items</span></div><div className="mt-4 space-y-3">{items.map(entry=><div key={entry.id} className={`rounded-xl border px-4 py-4 ${entry.active?"border-black/10":"border-black/5 opacity-55"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-medium">{entry.name}</div><div className="mt-1 text-xs text-black/50">{entry.description||"No description"}{entry.preparation_time_minutes?` · ${entry.preparation_time_minutes} min`:""}</div>{entry.restaurant_menu_item_options?.length? <div className="mt-2 text-xs text-black/50">Options: {entry.restaurant_menu_item_options.filter(o=>o.active!==false).map(o=>o.name).join(" · ")}</div>:null}</div><div className="text-right"><div className="font-medium">{entry.currency} {Number(entry.price).toLocaleString()}</div><div className="text-xs text-black/45">{entry.available?"Available":"Out of stock"}</div></div></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>editItem(entry)} className="rounded-full border border-black/10 px-3 py-1.5 text-xs">Edit</button><button onClick={()=>void toggleAvailable(entry)} className="rounded-full border border-black/10 px-3 py-1.5 text-xs">{entry.available?"Mark unavailable":"Mark available"}</button><button onClick={()=>void toggleItem(entry)} className="rounded-full border border-black/10 px-3 py-1.5 text-xs">{entry.active?"Deactivate":"Activate"}</button></div></div>)}{!items.length&&<p className="text-sm text-black/45">No menu items yet. Add your first item above.</p>}</div></section>
 {message&&<p className="mt-5 text-sm text-black/60">{message}</p>}</main>;
}
