import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase-server";
import { supabaseAdmin } from "@/lib/supabase-admin";

export default async function LocalVerificationPage() {
  const db=await createClient(); const {data:{user}}=await db.auth.getUser(); if(!user) redirect("/account/login?next=/locals/onboarding/verification");
  const {data:profile}=await db.from("local_profiles").select("id,display_name,personal_photo_url,verification_state,service_status").eq("user_id",user.id).maybeSingle();
  if(!profile) redirect("/locals/onboarding");
  const {data:verification}=await supabaseAdmin.from("verification_cases").select("id,status,verification_level,provider,created_at,reviewed_at,rejection_reason").eq("subject_type","local").eq("subject_id",profile.id).order("created_at",{ascending:false}).limit(1).maybeSingle();
  async function submit(){"use server"; const auth=await createClient();const {data:{user:current}}=await auth.auth.getUser();if(!current)redirect("/account/login?next=/locals/onboarding/verification");const {data:p}=await auth.from("local_profiles").select("id,personal_photo_url,languages,interests,terms_accepted_at").eq("user_id",current.id).maybeSingle();if(!p?.personal_photo_url||!p.languages?.length||!p.interests?.length||!p.terms_accepted_at)redirect("/locals/onboarding?error=complete-profile");const {data:open}=await supabaseAdmin.from("verification_cases").select("id").eq("subject_type","local").eq("subject_id",p.id).in("status",["not_started","pending","in_review"]).maybeSingle();if(!open)await supabaseAdmin.from("verification_cases").insert({subject_type:"local",subject_id:p.id,status:"pending",verification_level:"identity",provider:"human_review",notes:"Local identity/liveness review requested from authenticated onboarding flow."});await supabaseAdmin.from("local_profiles").update({verification_state:"pending",service_status:"pending_review",updated_at:new Date().toISOString()}).eq("id",p.id).neq("verification_state","verified");redirect("/locals/onboarding/verification?submitted=1");}
  return <main className="min-h-screen bg-[#f7f7f4] px-6 py-12"><div className="mx-auto max-w-2xl"><Link href="/locals/onboarding" className="text-sm font-semibold">← Local profile</Link><p className="mt-8 text-[11px] font-bold uppercase tracking-[.2em] text-black/40">Trust & safety</p><h1 className="mt-3 text-4xl font-semibold">Identity verification</h1><p className="mt-4 leading-7 text-black/55">SafariPlug requires identity review before a Local can become publicly active. Submitting starts a real review case; it does not claim that identity or liveness has already passed.</p><div className="mt-7 rounded-[2rem] bg-white p-6"><p className="text-sm"><b>Profile:</b> {profile.display_name}</p><p className="mt-2 text-sm"><b>Current verification:</b> {profile.verification_state}</p>{verification&&<p className="mt-2 text-sm"><b>Review case:</b> {verification.status} · {verification.verification_level}</p>}{verification?.rejection_reason&&<p className="mt-3 text-sm text-red-700">{verification.rejection_reason}</p>}{!verification||!["pending","in_review","approved"].includes(verification.status)?<form action={submit} className="mt-6"><button className="rounded-full bg-black px-6 py-3 text-sm font-bold text-white">Submit for identity review</button></form>:<div className="mt-6 rounded-2xl bg-[#f2f0e9] p-4 text-sm">Your verification case is {verification.status}. SafariPlug will not show a verified badge until the case is actually approved.</div>}</div><Link href="/locals/onboarding/availability" className="mt-5 inline-block text-sm font-semibold">Manage availability →</Link></div></main>;
}
