import Link from "next/link";
import { requireAdmin } from "@/lib/auth/require-admin";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const dynamic="force-dynamic";
type SupplierRow={id:string;onboarding_status:string;completion_percent:number|null;businesses:{name:string}[]};
type Prospect={id:string;business_name:string;category:string;city:string|null;status:string;opportunity_score:number|null;created_at:string};
const prospectStages=["pending_review","approved","contacted","pitch_sent","partnered"];
const humanAction=new Set(["pending_review","ready_for_approval","draft"]);
export default async function UnifiedCRM(){
 await requireAdmin();
 const [prospects,partners,invites,suppliers]=await Promise.all([
  supabaseAdmin.from("ai_sales_prospects").select("id,business_name,category,city,status,opportunity_score,created_at").order("created_at",{ascending:false}).limit(100),
  supabaseAdmin.from("safari_partners").select("id,outreach_stage"),
  supabaseAdmin.from("partner_invitations").select("id,business_name,partner_type,status,created_at").order("created_at",{ascending:false}).limit(50),
  supabaseAdmin.from("supplier_accounts").select("id,onboarding_status,completion_percent,businesses!inner(name)").order("created_at",{ascending:false}).limit(50),
 ]);
 const failed=[prospects.error&&"prospects",partners.error&&"relationships",invites.error&&"invitations",suppliers.error&&"suppliers"].filter(Boolean) as string[];
 const p=(prospects.data||[]) as Prospect[], i=invites.data||[], s=(suppliers.data||[]) as SupplierRow[], r=partners.data||[];
 const actionProspects=p.filter(x=>humanAction.has(x.status));const actionInvites=i.filter(x=>["draft","ready_for_approval"].includes(x.status));const actionSuppliers=s.filter(x=>!["approved","live"].includes(x.onboarding_status));
 return <main className="min-h-screen bg-[#070707] p-5 text-white md:p-10"><div className="mx-auto max-w-7xl"><header className="border-b border-zinc-800 pb-7"><p className="font-mono text-[11px] font-bold uppercase tracking-[.22em] text-amber-400">SafariPlug // AI Business OS</p><h1 className="mt-2 text-4xl font-bold">CRM 2.0</h1><p className="mt-2 max-w-3xl text-sm text-zinc-400">Lead discovery, qualification, governed outreach, recruitment, enrollment and partner management in one operating workspace. AI researches and drafts; people approve external actions.</p></header>
 {failed.length>0&&<div className="mt-5 rounded-2xl border border-red-900/60 bg-red-950/20 p-4 text-sm text-red-200">CRM data warning: {failed.join(", ")} could not be loaded. A failed query is not treated as zero activity.</div>}
 <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="AI prospects" value={p.length}/><Metric label="Relationships" value={r.length}/><Metric label="Needs human action" value={actionProspects.length+actionInvites.length}/><Metric label="Onboarding" value={actionSuppliers.length}/><Metric label="Active suppliers" value={s.filter(x=>["approved","live"].includes(x.onboarding_status)).length}/></section>
 <section className="mt-8"><Heading title="Lead pipeline" text="A live view of prospect movement. Stage changes remain governed by the existing sales workflow."/><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{prospectStages.map(stage=>{const rows=p.filter(x=>x.status===stage);return <Link key={stage} href="/admin/ai-sales" className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4 hover:border-amber-500/40"><p className="text-xs capitalize text-zinc-500">{stage.replaceAll("_"," ")}</p><p className="mt-2 text-3xl font-bold">{rows.length}</p><p className="mt-2 text-xs text-zinc-600">{rows.length?`Avg score ${Math.round(rows.reduce((a,x)=>a+Number(x.opportunity_score||0),0)/rows.length)}`:"No leads"}</p></Link>})}</div></section>
 <section className="mt-8 grid gap-3 md:grid-cols-3"><Action title="Discover with AI" text="Find and score real prospective SafariPlug partners." href="/admin/ai-sales"/><Action title="Review outreach" text="Review drafts and invitations before anything is sent externally." href="/admin/ai-sales/invitations"/><Action title="Enroll & manage" text="Track onboarding, verification, activation and Partner 360." href="/admin/ai-sales/partners"/></section>
 <div className="mt-8 grid gap-5 lg:grid-cols-2"><Panel title="Human approval queue" href="/admin/ai-sales">{actionProspects.slice(0,6).map(x=><Lead key={x.id} x={x}/>)}{actionInvites.slice(0,6).map(x=><Link href="/admin/ai-sales/invitations" key={x.id} className="block border-t border-zinc-900 py-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{x.business_name}</p><p className="text-xs text-zinc-500">Invitation · {x.partner_type}</p></div><span className="text-xs text-amber-300">{x.status.replaceAll("_"," ")}</span></div></Link>)}{!actionProspects.length&&!actionInvites.length&&<Empty text="No prospect or outreach approvals waiting."/>}</Panel>
 <Panel title="Priority prospects" href="/admin/ai-sales">{[...p].sort((a,b)=>Number(b.opportunity_score||0)-Number(a.opportunity_score||0)).slice(0,8).map(x=><Lead key={x.id} x={x}/>)}{!p.length&&<Empty text="No prospects discovered yet."/>}</Panel>
 <Panel title="Enrollment queue" href="/admin/ai-sales/partners">{actionSuppliers.slice(0,8).map(x=><Link href={`/admin/ai-sales/partners/${x.id}`} key={x.id} className="block border-t border-zinc-900 py-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{x.businesses[0]?.name||"Unnamed supplier"}</p><p className="text-xs text-zinc-500">{x.completion_percent||0}% onboarding</p></div><span className="text-xs text-amber-300">{x.onboarding_status.replaceAll("_"," ")}</span></div></Link>)}{!actionSuppliers.length&&<Empty text="No supplier onboarding actions waiting."/>}</Panel>
 <Panel title="AI workspaces" href="/admin"><div className="grid gap-2 pt-3"><Mini href="/admin/ai-sales" title="Partner Scout" text="Lead discovery, scoring and qualification"/><Mini href="/admin/ai-sales/invitations" title="Outreach Review" text="Human approval before external communication"/><Mini href="/admin/ai-sales/partners" title="Partner 360" text="Enrollment, verification and relationship operations"/><Mini href="/admin/ai-scout" title="Event Scout" text="Event discovery intelligence"/><Mini href="/admin/marketing" title="Amani Studio" text="Human-approved marketing drafts"/></div></Panel></div>
 <footer className="mt-8 flex flex-wrap gap-4 border-t border-zinc-800 pt-5 text-sm text-zinc-400"><Link href="/admin">← Command Center</Link><Link href="/admin/ai-sales">Lead Discovery</Link><Link href="/admin/ai-sales/partners">Partner CRM</Link><Link href="/admin/suppliers">Supplier Review</Link><Link href="/admin/accounting">Accounting</Link></footer></div></main>;
}
function Heading({title,text}:{title:string;text:string}){return <div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-zinc-500">{text}</p></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function Action({title,text,href}:{title:string;text:string;href:string}){return <Link href={href} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5 hover:border-amber-500/50"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p><p className="mt-4 text-sm font-semibold text-amber-400">Open →</p></Link>}
function Panel({title,href,children}:{title:string;href:string;children:React.ReactNode}){return <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="mb-3 flex justify-between"><h2 className="font-semibold">{title}</h2><Link href={href} className="text-sm text-amber-400">View all →</Link></div>{children}</section>}
function Lead({x}:{x:Prospect}){return <Link href={`/admin/ai-sales/edit/${x.id}`} className="block border-t border-zinc-900 py-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{x.business_name}</p><p className="text-xs text-zinc-500">{x.category} · {x.city||"city not recorded"}</p></div><div className="text-right"><p className="text-xs text-amber-300">{x.status.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-zinc-600">Score {x.opportunity_score??"—"}</p></div></div></Link>}
function Mini({href,title,text}:{href:string;title:string;text:string}){return <Link href={href} className="rounded-xl border border-zinc-900 p-3 hover:border-zinc-700"><p className="font-medium">{title}</p><p className="text-xs text-zinc-500">{text}</p></Link>}
function Empty({text}:{text:string}){return <p className="border-t border-zinc-900 py-5 text-sm text-zinc-500">{text}</p>}
