import Link from "next/link";
import { requireAdmin } from "@/lib/auth/require-admin";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const dynamic="force-dynamic";
export default async function UnifiedCRM(){
 await requireAdmin();
 const [prospects,partners,invites,suppliers]=await Promise.all([
  supabaseAdmin.from("ai_sales_prospects").select("id,business_name,category,city,status,opportunity_score,created_at").order("created_at",{ascending:false}).limit(8),
  supabaseAdmin.from("safari_partners").select("id,outreach_stage"),
  supabaseAdmin.from("partner_invitations").select("id,business_name,partner_type,status,created_at").order("created_at",{ascending:false}).limit(8),
  supabaseAdmin.from("supplier_accounts").select("id,onboarding_status,completion_percent,businesses!inner(name)").order("created_at",{ascending:false}).limit(8),
 ]);
 const p=prospects.data||[], i=invites.data||[], s=suppliers.data||[], r=partners.data||[];
 return <main className="min-h-screen bg-[#070707] p-5 text-white md:p-10"><div className="mx-auto max-w-7xl"><header className="border-b border-zinc-800 pb-7"><p className="font-mono text-[11px] font-bold uppercase tracking-[.22em] text-amber-400">SafariPlug // AI Business OS</p><h1 className="mt-2 text-4xl font-bold">AI CRM</h1><p className="mt-2 max-w-3xl text-sm text-zinc-400">One operating center for discovery, research, outreach, recruitment, enrollment, verification and partner management. AI drafts and assists; people approve external actions.</p></header>
 <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="AI prospects" value={p.length}/><Metric label="Relationships" value={r.length}/><Metric label="Invites need action" value={i.filter(x=>["draft","ready_for_approval","approved"].includes(x.status)).length}/><Metric label="Onboarding" value={s.filter(x=>!["approved","live"].includes(x.onboarding_status)).length}/><Metric label="Active" value={s.filter(x=>["approved","live"].includes(x.onboarding_status)).length}/></section>
 <section className="mt-7 grid gap-3 md:grid-cols-3"><Action title="1. Discover with AI" text="Find and score real prospective SafariPlug partners." href="/admin/ai-sales"/><Action title="2. Recruit & communicate" text="Draft governed outreach and invitations, then approve before sending." href="/admin/ai-sales/invitations"/><Action title="3. Enroll & manage" text="Track onboarding, verification, activation and Partner 360." href="/admin/ai-sales/partners"/></section>
 <div className="mt-8 grid gap-5 lg:grid-cols-2"><Panel title="AI prospect feed" href="/admin/ai-sales">{p.length?p.map(x=><Link href={`/admin/ai-sales/edit/${x.id}`} key={x.id} className="block border-t border-zinc-900 py-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{x.business_name}</p><p className="text-xs text-zinc-500">{x.category} · {x.city||"city not recorded"}</p></div><span className="text-xs text-amber-300">{x.status.replaceAll("_"," ")}</span></div></Link>):<Empty/>}</Panel>
 <Panel title="Recruitment queue" href="/admin/ai-sales/invitations">{i.length?i.map(x=><Link href="/admin/ai-sales/invitations" key={x.id} className="block border-t border-zinc-900 py-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{x.business_name}</p><p className="text-xs text-zinc-500">{x.partner_type}</p></div><span className="text-xs text-amber-300">{x.status.replaceAll("_"," ")}</span></div></Link>):<Empty/>}</Panel>
 <Panel title="Enrollment queue" href="/admin/ai-sales/partners">{s.length?s.map(x=><Link href={`/admin/ai-sales/partners/${x.id}`} key={x.id} className="block border-t border-zinc-900 py-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{Array.isArray(x.businesses)?x.businesses[0]?.name:x.businesses?.name}</p><p className="text-xs text-zinc-500">{x.completion_percent||0}% onboarding</p></div><span className="text-xs text-amber-300">{x.onboarding_status.replaceAll("_"," ")}</span></div></Link>):<Empty/>}</Panel>
 <Panel title="AI workspaces" href="/admin"><div className="grid gap-2 pt-3"><Mini href="/admin/ai-scout" title="Event Scout" text="Event discovery intelligence"/><Mini href="/admin/ai-sales" title="Partner Scout" text="Lead discovery and qualification"/><Mini href="/admin/marketing" title="Amani Studio" text="Human-approved marketing drafts"/></div></Panel></div>
 <footer className="mt-8 flex flex-wrap gap-4 border-t border-zinc-800 pt-5 text-sm text-zinc-400"><Link href="/admin">← Command Center</Link><Link href="/admin/ai-sales/partners">Partner CRM</Link><Link href="/admin/suppliers">Supplier Review</Link><Link href="/admin/payouts">Payouts</Link></footer></div></main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function Action({title,text,href}:{title:string;text:string;href:string}){return <Link href={href} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5 hover:border-amber-500/50"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p><p className="mt-4 text-sm font-semibold text-amber-400">Open →</p></Link>}
function Panel({title,href,children}:{title:string;href:string;children:React.ReactNode}){return <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="mb-3 flex justify-between"><h2 className="font-semibold">{title}</h2><Link href={href} className="text-sm text-amber-400">View all →</Link></div>{children}</section>}
function Mini({href,title,text}:{href:string;title:string;text:string}){return <Link href={href} className="rounded-xl border border-zinc-900 p-3"><p className="font-medium">{title}</p><p className="text-xs text-zinc-500">{text}</p></Link>}
function Empty(){return <p className="border-t border-zinc-900 py-5 text-sm text-zinc-500">No records yet.</p>}
