"use client";

import { useEffect, useState } from "react";

const statuses = ["pending", "accepted", "preparing", "ready", "driver_assigned", "picked_up", "on_the_way", "delivered"];
const labels: Record<string,string> = { pending:"New", accepted:"Accepted", preparing:"Preparing", ready:"Ready", driver_assigned:"Driver assigned", picked_up:"Picked up", on_the_way:"On the way", delivered:"Delivered", rejected:"Rejected", cancelled:"Cancelled" };

type Order = { id:string; public_id?:string|null; status:string; payment_status:string; fulfillment_method:string; currency:string; customer_total:number; customer_name?:string|null; customer_phone?:string|null; delivery_address?:string|null; customer_notes?:string|null; eta_at?:string|null; created_at:string; food_order_items?:{item_name:string;quantity:number;line_total:number}[] };

export default function RestaurantOrdersPage(){
 const [orders,setOrders]=useState<Order[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
 async function load(){const r=await fetch("/api/restaurants/orders/status",{cache:"no-store"});const d=await r.json();if(!r.ok){setError(d.error||"Unable to load orders");return}setOrders(d.orders||[]);setError("")}
 useEffect(()=>{void load();const id=setInterval(()=>void load(),15000);return()=>clearInterval(id)},[]);
 async function transition(orderId:string,status:string){setBusy(orderId+status);try{const r=await fetch("/api/restaurants/orders/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId,status})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Update failed");await load()}catch(e:any){setError(e.message)}finally{setBusy("")}}
 function next(o:Order){if(o.status==="pending")return [["accepted","Accept"],["rejected","Reject"]];if(o.status==="accepted")return [["preparing","Start preparing"]];if(o.status==="preparing")return [["ready","Mark ready"]];if(o.status==="ready")return [["driver_assigned","Confirm driver"]];if(o.status==="driver_assigned")return [["picked_up","Mark picked up"]];if(o.status==="picked_up")return [["on_the_way","Start delivery"]];if(o.status==="on_the_way")return [["delivered","Complete delivery"]];return []}
 return <main className="min-h-screen bg-slate-50 px-5 py-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-amber-700">SafariPlug Restaurant Operations</p><h1 className="mt-2 text-4xl font-semibold">Orders</h1><p className="mt-2 text-slate-600">Accept orders, manage preparation and hand off deliveries.</p></div><button onClick={()=>void load()} className="rounded-full border bg-white px-4 py-2 text-sm font-semibold">Refresh</button></div>{error&&<div className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-8 grid gap-5 lg:grid-cols-2">{orders.map(o=><article key={o.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><p className="text-sm font-semibold">Order {o.public_id||o.id}</p><p className="mt-1 text-lg font-semibold">{o.customer_name||"Customer"}</p><p className="text-xs text-slate-500">{new Date(o.created_at).toLocaleString()} · {o.fulfillment_method.replaceAll("_"," ")}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{labels[o.status]||o.status}</span></div><div className="mt-5 space-y-2">{(o.food_order_items||[]).map((i,n)=><div key={n} className="flex justify-between text-sm"><span>{i.quantity} × {i.item_name}</span><span>{o.currency} {Number(i.line_total).toLocaleString()}</span></div>)}</div><div className="mt-4 border-t pt-4 text-sm text-slate-600"><p><strong>Total:</strong> {o.currency} {Number(o.customer_total).toLocaleString()} · <strong>Payment:</strong> {o.payment_status}</p>{o.delivery_address&&<p className="mt-1"><strong>Deliver to:</strong> {o.delivery_address}</p>}{o.customer_notes&&<p className="mt-1"><strong>Note:</strong> {o.customer_notes}</p>}</div><div className="mt-5 flex flex-wrap gap-2">{next(o).map(([status,text])=><button key={status} disabled={busy===o.id+status} onClick={()=>void transition(o.id,status)} className={`rounded-full px-4 py-2 text-sm font-semibold ${status==="rejected"?"border":"bg-black text-white"} disabled:opacity-50`}>{busy===o.id+status?"Updating…":text}</button>)}</div></article>)}{!orders.length&&!error&&<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-slate-500 lg:col-span-2">No restaurant orders yet.</div>}</div></div></main>
}
