"use server";
import OpenAI from "openai";import {Resend} from "resend";import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {requireAdmin} from "@/lib/auth/require-admin";import {supabaseAdmin} from "@/lib/supabase-admin";
const PATH="/admin/ai-sales/invitations";function clean(v:FormDataEntryValue|null){return typeof v==="string"?v.trim():""}function isUsableEmail(v:unknown){if(typeof v!=="string")return false;const e=v.trim(),l=e.toLowerCase();if(!e||l.includes("[email")||l.includes("protected")||l.includes("example.")||l.includes("noreply")||l.includes("no-reply")||/[\[\]<>\s]/.test(e))return false;return /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(e)}function sendResult(kind:"sent"|"error",message:string):never{redirect(`${PATH}?${kind}=${encodeURIComponent(message)}`)}
export async function createPartnerInvitation(_fd:FormData){await requireAdmin();throw new Error("Unlinked partner invitations are disabled. Open the organization in CRM / Organization 360 and create outreach from its governed context.");}
export async function draftPartnerInvitation(fd:FormData){await requireAdmin();const id=clean(fd.get("id"));const prospectId=clean(fd.get("prospect_id"));const scopedPath=prospectId?`${PATH}?prospect_id=${encodeURIComponent(prospectId)}`:PATH;try{if(!process.env.OPENAI_API_KEY)throw new Error("OpenAI drafting is not configured on the server.");const {data:i,error}=await supabaseAdmin.from("partner_invitations").select("id,business_name,partner_type,contact_email,whatsapp_phone,invitation_token").eq("id",id).single();if(error||!i)throw new Error(error?.message||"Invitation not found");const join=`${(process.env.NEXT_PUBLIC_SITE_URL||"https://www.safariplug.com").replace(/\/$/,"")}/partners/join/${i.invitation_token}`;const openai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await openai.responses.create({model:process.env.OPENAI_SALES_SCOUT_MODEL||"gpt-5-mini",input:`You are SafariPlug's governed partnership outreach assistant. Draft a concise, personalized recruitment invitation using ONLY these known facts: business=${i.business_name}; partner type=${i.partner_type}; channel=${i.contact_email?"email":"WhatsApp"}. Explain SafariPlug helps travelers discover and book trusted African travel, hospitality and local services. Explain the partner controls profile, offerings, rates and availability. Signup does not automatically verify or activate them; onboarding/compliance still applies. Include this exact signup link: ${join}. If the business value is exactly "Invited supplier", that is an internal placeholder because the business name is unknown: do not address them by that phrase and keep the invitation generic. Never invent a contact name, business name, business achievement, relationship, rate, booking volume, earnings, verification or guarantee. Keep claims factual and professional. Return exactly: SUBJECT: <subject> then MESSAGE: <plain-text message>.`});const text=r.output_text.trim(),m=text.match(/SUBJECT:\s*(.+?)\s*MESSAGE:\s*([\s\S]+)/i),subject=m?.[1]?.trim()||(i.business_name==="Invited supplier"?"Invitation to join SafariPlug":`Invitation to join SafariPlug — ${i.business_name}`),message=m?.[2]?.trim()||text;const {data:updated,error:u}=await supabaseAdmin.from("partner_invitations").update({ai_subject:subject,ai_message:message,status:"ready_for_approval",updated_at:new Date().toISOString()}).eq("id",id).eq("status","draft").select("id").maybeSingle();if(u)throw new Error(u.message);if(!updated)throw new Error("This invitation is no longer in draft status. Refresh the page and try again.");revalidatePath(PATH);redirect(scopedPath)}catch(error){const message=error instanceof Error?error.message:"Unable to generate AI draft.";redirect(`${scopedPath}${scopedPath.includes("?")?"&":"?"}error=${encodeURIComponent(message)}`)}}
export async function approvePartnerInvitation(fd:FormData){await requireAdmin();const id=clean(fd.get("id")),subject=clean(fd.get("subject")),message=clean(fd.get("message"));if(!subject||!message)throw new Error("Subject and message are required.");const {error}=await supabaseAdmin.from("partner_invitations").update({ai_subject:subject,ai_message:message,status:"approved",approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).eq("status","ready_for_approval");if(error)throw new Error(error.message);revalidatePath(PATH)}
export async function returnInvitationToDraft(fd:FormData){await requireAdmin();const id=clean(fd.get("id"));const {error}=await supabaseAdmin.from("partner_invitations").update({status:"ready_for_approval",approved_at:null,updated_at:new Date().toISOString()}).eq("id",id).eq("status","approved");if(error)throw new Error(error.message);revalidatePath(PATH)}
export async function sendPartnerInvitation(fd:FormData){await requireAdmin();const id=clean(fd.get("id"));let result:{kind:"sent"|"error";message:string};try{const {data:i,error}=await supabaseAdmin.from("partner_invitations").select("*").eq("id",id).single();if(error||!i){result={kind:"error",message:error?.message||"Invitation not found"}}else if(i.status!=="approved"){result={kind:"error",message:"Invitation must be approved before sending."}}else if(!i.ai_subject||!i.ai_message){result={kind:"error",message:"Approved invitation is missing its subject or message."}}else if(i.contact_email){if(!isUsableEmail(i.contact_email)){result={kind:"error",message:"This invitation has an invalid or placeholder email address. Nothing was sent."}}else if(!process.env.RESEND_API_KEY){result={kind:"error",message:"Email delivery is not configured on the server. Nothing was sent."}}else{const resend=new Resend(process.env.RESEND_API_KEY);const sent=await resend.emails.send({from:process.env.OUTREACH_FROM_EMAIL||"SafariPlug <onboarding@resend.dev>",to:i.contact_email,subject:i.ai_subject,text:i.ai_message,tags:[{name:"email_kind",value:"partner_invitation"},{name:"invitation_id",value:i.id}]});if(sent.error){result={kind:"error",message:`Email provider rejected the send: ${sent.error.message}`}}else{const now=new Date().toISOString();const {data:updated,error:u}=await supabaseAdmin.from("partner_invitations").update({status:"sent",sent_at:now,updated_at:now}).eq("id",id).eq("status","approved").select("id").maybeSingle();if(u||!updated){result={kind:"error",message:"Email was delivered, but SafariPlug could not record the sent status. Check the invitation before sending again."}}else{
    const warnings:string[]=[];
    if(i.prospect_id){
      const {error:prospectStageError}=await supabaseAdmin.from("ai_sales_prospects").update({status:"contacted",updated_at:now}).eq("id",i.prospect_id);
      if(prospectStageError){console.error("Invitation sent but prospect stage sync failed",prospectStageError);warnings.push("prospect stage");}
      const {error:activityError}=await supabaseAdmin.from("crm_activities").insert({prospect_id:i.prospect_id,partner_id:i.partner_id||null,contact_id:i.contact_id||null,activity_type:"email",summary:"Approved partner invitation sent",details:`Invitation ${i.id} was sent after human approval.`});
      if(activityError){console.error("Invitation sent but CRM activity logging failed",activityError);warnings.push("CRM activity");}
      const dueAt=new Date(Date.now()+3*24*60*60*1000).toISOString();
      const {data:existingFollowup,error:followupLookupError}=await supabaseAdmin.from("crm_followups").select("id").eq("prospect_id",i.prospect_id).eq("status","open").ilike("title","%invitation%").limit(1).maybeSingle();
      if(followupLookupError){console.error("Invitation sent but follow-up lookup failed",followupLookupError);warnings.push("follow-up");}
      else if(!existingFollowup){
        const {error:followupError}=await supabaseAdmin.from("crm_followups").insert({prospect_id:i.prospect_id,title:"Follow up on partner invitation",due_at:dueAt,priority:"normal",notes:`Invitation ${i.id} sent; review response or opening status.`});
        if(followupError){console.error("Invitation sent but follow-up scheduling failed",followupError);warnings.push("follow-up");}
      }
    }
    if(i.partner_id){
      const {error:partnerStageError}=await supabaseAdmin.from("safari_partners").update({outreach_stage:"contacted"}).eq("id",i.partner_id);
      if(partnerStageError){console.error("Invitation sent but partner stage sync failed",partnerStageError);warnings.push("relationship stage");}
    }
    revalidatePath(PATH);revalidatePath("/admin/crm");
    result={kind:"sent",message:warnings.length?"Invitation sent successfully. CRM sync needs review for: "+warnings.join(", ")+".":"Invitation sent successfully. Follow-up scheduled."};
  }}}}else if(i.whatsapp_phone){result={kind:"error",message:"No real WhatsApp Business provider is configured. Nothing was sent."}}else{result={kind:"error",message:"This invitation has no contact method. Nothing was sent."}}}catch(error){console.error("Partner invitation send failed",error);result={kind:"error",message:error instanceof Error?error.message:"Unable to send the invitation. Nothing was marked sent."}}return sendResult(result.kind,result.message)}
