"use server";
import OpenAI from "openai";
import {Resend} from "resend";
import {revalidatePath} from "next/cache";
import {requireAdmin} from "@/lib/auth/require-admin";
import {supabaseAdmin} from "@/lib/supabase-admin";
const PATH="/admin/ai-sales/invitations";
function clean(v:FormDataEntryValue|null){return typeof v==="string"?v.trim():""}
export async function createPartnerInvitation(fd:FormData){const admin=await requireAdmin();const business_name=clean(fd.get("business_name"));const partner_type=clean(fd.get("partner_type"));const contact_email=clean(fd.get("contact_email")).toLowerCase()||null;const whatsapp_phone=clean(fd.get("whatsapp_phone"))||null;if(!business_name||!partner_type||(!contact_email&&!whatsapp_phone))throw new Error("Business name, partner type and at least one contact method are required.");const channel=contact_email&&whatsapp_phone?"both":contact_email?"email":"whatsapp";const {error}=await supabaseAdmin.from("partner_invitations").insert({business_name,partner_type,contact_email,whatsapp_phone,channel,created_by:admin.id,status:"draft"});if(error)throw new Error(error.message);revalidatePath(PATH)}
export async function draftPartnerInvitation(fd:FormData){await requireAdmin();if(!process.env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is not configured");const id=clean(fd.get("id"));const {data:i,error}=await supabaseAdmin.from("partner_invitations").select("id,business_name,partner_type,contact_email,whatsapp_phone,invitation_token").eq("id",id).single();if(error||!i)throw new Error(error?.message||"Invitation not found");const join=`${(process.env.NEXT_PUBLIC_SITE_URL||"https://www.safariplug.com").replace(/\/$/,"")}/partners/join/${i.invitation_token}`;const openai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await openai.responses.create({model:process.env.OPENAI_SALES_SCOUT_MODEL||"gpt-5-mini",input:`Draft a concise professional SafariPlug partner recruitment invitation. Business: ${i.business_name}. Partner type: ${i.partner_type}. Explain SafariPlug helps travelers discover and book trusted African travel, hospitality and local services. Explain they control their profile, offerings, rates and availability. Signing up does not automatically verify or activate them; required onboarding/compliance still applies. Include this exact signup link: ${join}. Do not claim guaranteed bookings, earnings, verification, or activation. Return exactly: SUBJECT: <subject> then MESSAGE: <plain-text message>.`});const text=r.output_text.trim();const m=text.match(/SUBJECT:\s*(.+?)\s*MESSAGE:\s*([\s\S]+)/i);const subject=m?.[1]?.trim()||`Invitation to join SafariPlug — ${i.business_name}`;const message=m?.[2]?.trim()||text;const {error:u}=await supabaseAdmin.from("partner_invitations").update({ai_subject:subject,ai_message:message,status:"ready_for_approval",updated_at:new Date().toISOString()}).eq("id",id);if(u)throw new Error(u.message);revalidatePath(PATH)}
export async function approvePartnerInvitation(fd:FormData){await requireAdmin();const id=clean(fd.get("id"));const subject=clean(fd.get("subject"));const message=clean(fd.get("message"));if(!subject||!message)throw new Error("Subject and message are required.");const {error}=await supabaseAdmin.from("partner_invitations").update({ai_subject:subject,ai_message:message,status:"approved",approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).in("status",["ready_for_approval","draft"]);if(error)throw new Error(error.message);revalidatePath(PATH)}
export async function sendPartnerInvitation(fd:FormData){await requireAdmin();const id=clean(fd.get("id"));const {data:i,error}=await supabaseAdmin.from("partner_invitations").select("*").eq("id",id).single();if(error||!i)throw new Error(error?.message||"Invitation not found");if(i.status!=="approved")throw new Error("Invitation must be approved before sending.");if(i.contact_email){if(!process.env.RESEND_API_KEY)throw new Error("RESEND_API_KEY is not configured; invitation was not sent.");const resend=new Resend(process.env.RESEND_API_KEY);const sent=await resend.emails.send({from:process.env.OUTREACH_FROM_EMAIL||"SafariPlug <onboarding@resend.dev>",to:i.contact_email,subject:i.ai_subject,text:i.ai_message});if(sent.error)throw new Error(sent.error.message)}if(!i.contact_email&&i.whatsapp_phone)throw new Error("No real WhatsApp Business provider is configured for partner invitations. Nothing was sent.");const {error:u}=await supabaseAdmin.from("partner_invitations").update({status:"sent",sent_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(u)throw new Error(u.message);revalidatePath(PATH)}
