import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase-server";
import LocalPhotoUpload from "./LocalPhotoUpload";

export default async function LocalOnboardingPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/account/login?next=/locals/onboarding");
  const { data: profile } = await supabase.from("local_profiles").select("*").eq("user_id", user.id).maybeSingle();

  async function save(formData: FormData) { "use server";
    const db = await createClient(); const { data: { user: current } } = await db.auth.getUser(); if (!current) redirect("/account/login?next=/locals/onboarding");
    const split=(name:string)=>String(formData.get(name)||"").split(",").map(x=>x.trim()).filter(Boolean);
    const photo=String(formData.get("personal_photo_url")||"").trim();
    const expected=`/storage/v1/object/public/local-profile-photos/${current.id}/`;
    const payload={user_id:current.id,display_name:String(formData.get("display_name")||"").trim(),bio:String(formData.get("bio")||"").trim()||null,personal_photo_url:photo||null,city:String(formData.get("city")||"").trim()||null,country:String(formData.get("country")||"").trim()||null,languages:split("languages"),interests:split("interests"),specialties:split("specialties"),hourly_rate:formData.get("hourly_rate")?Number(formData.get("hourly_rate")):null,currency:String(formData.get("currency")||"USD").trim().toUpperCase(),terms_accepted_at:new Date().toISOString()};
    if (!payload.display_name || !photo.includes(expected) || !payload.languages.length || !payload.interests.length) redirect("/locals/onboarding?error=required");
    const existing=await db.from("local_profiles").select("id,service_status,verification_state").eq("user_id",current.id).maybeSingle();
    if(existing.data){ if(existing.data.service_status==="active"||existing.data.verification_state==="verified") redirect("/locals/onboarding?error=locked"); await db.from("local_profiles").update(payload).eq("id",existing.data.id); }
    else await db.from("local_profiles").insert(payload);
    redirect("/locals/onboarding?success=1");
  }

  return <main className="min-h-screen bg-[#f7f7f4] px-6 py-12 text-black"><div className="mx-auto max-w-3xl"><Link href="/locals" className="text-sm font-semibold">← Locals</Link><p className="mt-8 text-[11px] font-bold uppercase tracking-[.2em] text-black/40">Local onboarding</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Build your personal Local profile</h1><p className="mt-3 text-sm leading-6 text-black/55">Your personal photo is required. Saving this profile does not make you public or verified; SafariPlug verification and activation are separate gates.</p>
  {profile && <div className="mt-6 rounded-2xl bg-white p-4 text-sm"><b>Status:</b> {profile.service_status} · <b>Verification:</b> {profile.verification_state}</div>}
  <form action={save} className="mt-7 grid gap-5 rounded-[2rem] bg-white p-6 sm:p-8"><label className="grid gap-2 text-sm font-semibold">Display name<input name="display_name" required defaultValue={profile?.display_name||""} className="rounded-xl border p-3 font-normal"/></label><LocalPhotoUpload userId={user.id} initialUrl={profile?.personal_photo_url}/><label className="grid gap-2 text-sm font-semibold">Bio<textarea name="bio" defaultValue={profile?.bio||""} rows={4} className="rounded-xl border p-3 font-normal"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">City<input name="city" defaultValue={profile?.city||""} className="rounded-xl border p-3 font-normal"/></label><label className="grid gap-2 text-sm font-semibold">Country<input name="country" defaultValue={profile?.country||""} className="rounded-xl border p-3 font-normal"/></label></div><label className="grid gap-2 text-sm font-semibold">Languages *<input name="languages" required defaultValue={(profile?.languages||[]).join(", ")} placeholder="English, Swahili" className="rounded-xl border p-3 font-normal"/></label><label className="grid gap-2 text-sm font-semibold">Interests *<input name="interests" required defaultValue={(profile?.interests||[]).join(", ")} placeholder="Food, nightlife, culture, photography" className="rounded-xl border p-3 font-normal"/></label><label className="grid gap-2 text-sm font-semibold">Specialties<input name="specialties" defaultValue={(profile?.specialties||[]).join(", ")} placeholder="Hidden gems, city orientation" className="rounded-xl border p-3 font-normal"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Hourly rate<input name="hourly_rate" type="number" min="0" step="0.01" defaultValue={profile?.hourly_rate??""} className="rounded-xl border p-3 font-normal"/></label><label className="grid gap-2 text-sm font-semibold">Currency<input name="currency" maxLength={3} defaultValue={profile?.currency||"USD"} className="rounded-xl border p-3 font-normal"/></label></div><div className="rounded-2xl bg-[#f2f0e9] p-4 text-xs leading-5 text-black/55"><b>Verification gate:</b> your photo and profile are saved first. SafariPlug identity/liveness verification remains a separate review step. A saved profile is never automatically marked verified or activated.</div><p className="text-xs leading-5 text-black/45">By saving, you confirm the information and photo belong to you and agree to SafariPlug Local terms. Verification is a trust signal, not a guarantee of safety.</p><button className="rounded-full bg-black px-6 py-4 text-sm font-bold text-white">Save Local profile</button></form></div></main>;
}
