"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type State = { account?: { contact_name: string; onboarding_status: string; completion_percent: number }; business?: Record<string, any>; profile?: Record<string, any>; offerings?: Record<string, any>[] };

export default function SupplierOnboardingPage() {
  const [state, setState] = useState<State>({});
  const [form, setForm] = useState<Record<string, any>>({});
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  async function load() { const r = await fetch("/api/supplier/onboarding", { cache: "no-store" }); if (r.ok) { const data = await r.json(); setState(data); setForm({ ...data.business, ...data.profile }); } else setMessage("Please use the invitation email to access your supplier portal."); }
  useEffect(() => { void load(); }, []);
  const set = (key: string, value: any) => setForm((f) => ({ ...f, [key]: value }));
  async function createPassword() { setMessage(""); if (password.length < 8) return setMessage("Password must be at least 8 characters."); if (password !== confirmPassword) return setMessage("Passwords do not match."); const { error } = await supabase.auth.updateUser({ password }); setMessage(error ? error.message : "Password created successfully."); if (!error) { setPassword(""); setConfirmPassword(""); void load(); } }
  async function save() { setSaving(true); setMessage(""); const r = await fetch("/api/supplier/onboarding", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await r.json(); setMessage(r.ok ? `Saved. Profile completion: ${data.completion_percent}%` : data.error || "Unable to save."); setSaving(false); void load(); }
  async function addOffering() { const name = window.prompt("Service name"); if (!name) return; const price = window.prompt("Price in KES", "0"); const duration = window.prompt("Duration in minutes", "60"); const r = await fetch("/api/supplier/onboarding", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "offering", offering: { name, price, duration_minutes: duration, currency: "KES" } }) }); const data = await r.json(); setMessage(r.ok ? "Service saved as draft." : data.error || "Unable to save service."); void load(); }
  async function submit() { const r = await fetch("/api/supplier/onboarding", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "submit" }) }); const data = await r.json(); setMessage(r.ok ? "Submitted. SafariPlug will review your profile." : data.error || "Unable to submit."); void load(); }
  if (!state.business) return <main className="mx-auto max-w-3xl px-6 py-16"><h1 className="text-3xl font-semibold">SafariPlug Supplier Portal</h1><p className="mt-3 text-black/60">{message || "Loading your supplier profile…"}</p></main>;
  const locked = ["approved", "live"].includes(state.account?.onboarding_status || "");
  return <main className="mx-auto max-w-4xl px-6 py-10"><div className="flex items-end justify-between gap-6"><div><p className="text-sm uppercase tracking-[.2em] text-black/40">Supplier Portal</p><h1 className="mt-2 text-4xl font-semibold">Finish your SafariPlug profile</h1><p className="mt-2 text-black/60">Welcome, {state.account?.contact_name}. Complete your details, services and images.</p></div><div className="text-right"><div className="text-3xl font-semibold">{state.account?.completion_percent ?? 0}%</div><div className="text-xs text-black/50">profile complete</div></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full bg-black transition-all" style={{ width: `${state.account?.completion_percent ?? 0}%` }} /></div>
    <section className="mt-8 rounded-2xl border border-black/10 p-5"><h2 className="text-xl font-semibold">Create your password</h2><p className="mt-1 text-sm text-black/50">SafariPlug never sees or stores your password. It is managed securely by your account.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input type="password" placeholder="New password (8+ characters)" value={password} onChange={(e) => setPassword(e.target.value)} className="rounded-xl border border-black/15 px-3 py-2.5" /><input type="password" placeholder="Confirm password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} className="rounded-xl border border-black/15 px-3 py-2.5" /></div><button onClick={createPassword} className="mt-3 rounded-full bg-black px-5 py-2.5 text-sm text-white">Save password</button></section>
    <section className="mt-8 grid gap-5 md:grid-cols-2">{[["name","Business name"],["supplier_contact_name","Contact person"],["phone","Phone"],["whatsapp","WhatsApp"],["email","Email"],["address","Address"],["website_url","Website"],["instagram_url","Instagram"],["facebook_url","Facebook"],["tiktok_url","TikTok"]].map(([key,label]) => <label key={key} className="text-sm"><span className="mb-1 block font-medium">{label}</span><input disabled={locked || key === "email"} value={form[key] || ""} onChange={(e) => set(key,e.target.value)} className="w-full rounded-xl border border-black/15 px-3 py-2.5" /></label>)}<label className="text-sm md:col-span-2"><span className="mb-1 block font-medium">Business description</span><textarea disabled={locked} value={form.description || ""} onChange={(e) => set("description",e.target.value)} rows={5} className="w-full rounded-xl border border-black/15 px-3 py-2.5" /></label><label className="text-sm"><span className="mb-1 block font-medium">Timezone</span><input disabled={locked} value={form.timezone || "Africa/Nairobi"} onChange={(e) => set("timezone",e.target.value)} className="w-full rounded-xl border border-black/15 px-3 py-2.5" /></label><label className="text-sm"><span className="mb-1 block font-medium">Cancellation policy</span><input disabled={locked} value={form.cancellation_policy || ""} onChange={(e) => set("cancellation_policy",e.target.value)} className="w-full rounded-xl border border-black/15 px-3 py-2.5" /></label></section>
    <section className="mt-10 rounded-2xl border border-black/10 p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Services & pricing</h2><p className="text-sm text-black/50">Add the services customers can book.</p></div><button onClick={addOffering} disabled={locked} className="rounded-full bg-black px-4 py-2 text-sm text-white disabled:opacity-40">Add service</button></div><div className="mt-5 space-y-2">{(state.offerings || []).map((o) => <div key={o.id} className="flex justify-between rounded-xl bg-black/[.04] px-4 py-3 text-sm"><span>{o.name}</span><span>KES {Number(o.price).toLocaleString()} · {o.duration_minutes} min · {o.status}</span></div>)}{!(state.offerings || []).length && <p className="text-sm text-black/45">No services added yet.</p>}</div></section>
    <section className="mt-6 rounded-2xl border border-black/10 p-5"><h2 className="text-xl font-semibold">Images</h2><p className="mt-1 text-sm text-black/50">Supplier media storage is ready for logo, cover and gallery images.</p></section>
    <div className="mt-6 flex flex-wrap items-center gap-3"><button onClick={save} disabled={saving || locked} className="rounded-full border border-black/15 px-5 py-2.5 text-sm disabled:opacity-40">{saving ? "Saving…" : "Save profile"}</button><button onClick={submit} disabled={locked} className="rounded-full bg-black px-5 py-2.5 text-sm text-white disabled:opacity-40">Submit for review</button>{state.account?.onboarding_status && <span className="text-sm text-black/50">Status: {state.account.onboarding_status}</span>}</div>{message && <p className="mt-4 text-sm">{message}</p>}</main>;
}
