import Link from "next/link";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { SupplierScoutForm } from "./supplier-scout-form";

export default async function AISalesPage(){
 const [{count:total},{count:pending},{count:partners},{count:invites},{count:signupStarted}]=await Promise.all([
  supabaseAdmin.from("ai_sales_prospects").select("*",{count:"exact",head:true}),
  supabaseAdmin.from("ai_sales_prospects").select("*",{count:"exact",head:true}).eq("review_status","pending_review"),
  supabaseAdmin.from("ai_sales_prospects").select("*",{count:"exact",head:true}).eq("status","partner"),
  supabaseAdmin.from("partner_invitations").select("*",{count:"exact",head:true}),
  supabaseAdmin.from("partner_invitations").select("*",{count:"exact",head:true}).in("status",["signup_started","onboarding"]),
 ]);
 const {data:prospects}=await supabaseAdmin.from("ai_sales_prospects").select("id,business_name,category,city,opportunity_score,status,review_status").order("created_at",{ascending:false}).limit(20);
 return <main className="min-h-screen bg-gray-50 p-5 md:p-8"><div className="mx-auto max-w-6xl"><Link href="/admin" className="text-blue-600 hover:underline">← Back to Admin</Link><div className="mt-6 rounded-2xl bg-white p-6 shadow md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-gray-400">Partner Growth</p><h1 className="mt-2 text-3xl font-bold">SafariPlug AI Sales Agent</h1><p className="mt-2 text-gray-600">Discover, recruit and move real partners into SafariPlug onboarding.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/ai-sales/invitations" className="rounded-xl bg-amber-500 px-5 py-3 font-semibold text-black">✉ Invite Partner</Link><Link href="/admin/ai-sales/partners" className="rounded-xl bg-black px-5 py-3 text-white">Open Partner CRM →</Link></div></div>
 <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Prospects",total],["Pending review",pending],["CRM partners",partners],["Invitations",invites],["Onboarding",signupStarted]].map(([label,value])=><div key={String(label)} className="rounded-xl border p-4"><p className="text-sm text-gray-500">{label}</p><p className="mt-1 text-3xl font-bold">{Number(value)||0}</p></div>)}</div>
 <section className="mt-8 grid gap-3 md:grid-cols-3"><Link href="#scout" className="rounded-xl border p-5 hover:border-black"><h2 className="font-semibold">1. Discover</h2><p className="mt-2 text-sm text-gray-500">Find real prospects with AI Supplier Scout.</p></Link><Link href="/admin/ai-sales/invitations" className="rounded-xl border p-5 hover:border-amber-500"><h2 className="font-semibold">2. Invite</h2><p className="mt-2 text-sm text-gray-500">AI drafts. You review and approve before sending.</p></Link><Link href="/admin/ai-sales/partners" className="rounded-xl border p-5 hover:border-black"><h2 className="font-semibold">3. Manage</h2><p className="mt-2 text-sm text-gray-500">See recruitment, onboarding and relationship activity together.</p></Link></section>
 <section id="scout" className="mt-8 rounded-xl border p-6"><h2 className="text-xl font-semibold">Africa Supplier Scout</h2><p className="mt-2 text-gray-600">Discovery only: results are reviewed before outreach. The button shows live run status and prevents duplicate submissions.</p><SupplierScoutForm/></section>
 <section className="mt-8 rounded-xl border p-6"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold">Prospect Feed</h2><p className="mt-1 text-sm text-gray-500">Review a prospect, then invite them from the Partner CRM.</p></div><Link href="/admin/ai-sales/invitations" className="text-sm font-semibold text-amber-700">Invite Partner →</Link></div><div className="mt-5 space-y-3">{prospects?.map(p=><div key={p.id} className="rounded-xl border p-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h3 className="text-lg font-bold">{p.business_name}</h3><p className="text-gray-600">{p.city} · {p.category}</p><p className="mt-1 text-sm">Opportunity <b>{p.opportunity_score??0}%</b> · {p.status} · {p.review_status}</p></div><div className="flex gap-3 text-sm"><Link href={`/admin/ai-sales/edit/${p.id}`} className="text-blue-600 hover:underline">Review →</Link><Link href="/admin/ai-sales/invitations" className="font-semibold text-amber-700 hover:underline">Invite →</Link></div></div></div>)}</div></section>
 </div></div></main>
}
