import { useCallback, useEffect, useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { supabase } from "../../src/auth";
import { API_BASE_URL } from "../../src/config";
import { ErrorBlock, LoadingBlock } from "../../src/components/StatusBlocks";
import { colors } from "../../src/theme";

type Appointment={id:string;public_id?:string;starts_at:string;status:string;price:number;currency:string;payment_status:string;service_profiles?:{businesses?:{name?:string}};service_offerings?:{name?:string}};
const labels:Record<string,string>={pending:"Awaiting confirmation",confirmed:"Confirmed",checked_in:"Checked in",in_progress:"In progress",completed:"Completed",cancelled:"Cancelled",no_show:"No show"};
export default function AppointmentsScreen(){const[items,setItems]=useState<Appointment[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setError(null);try{const{data}=await supabase.auth.getSession();if(!data.session)throw new Error("Sign in to see your service bookings.");const r=await fetch(`${API_BASE_URL}/api/account/appointments`,{headers:{accept:"application/json",authorization:`Bearer ${data.session.access_token}`}});const b=await r.json();if(!r.ok)throw new Error(b?.error||"Unable to load bookings.");setItems(b.appointments||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load bookings.")}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load()},[load]);return<SafeAreaView style={styles.safe} edges={["top"]}>{loading?<LoadingBlock label="Loading bookings…"/>:error?<ScrollView contentContainerStyle={styles.page}><ErrorBlock message={error} onRetry={()=>void load()}/></ScrollView>:<ScrollView contentContainerStyle={styles.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>}><View style={styles.hero}><Text style={styles.kicker}>SafariPlug Services</Text><Text style={styles.title}>My bookings</Text><Text style={styles.body}>Real appointment confirmations, payment state and provider status.</Text></View>{!items.length?<View style={styles.empty}><Text style={styles.heading}>No service bookings yet</Text><Text style={styles.body}>Choose a service to see live providers and available appointment times.</Text></View>:items.map(a=><Pressable key={a.id} style={styles.card} onPress={()=>router.push({pathname:"/appointment/[appointmentId]",params:{appointmentId:a.id}})}><Text style={styles.provider}>{a.service_profiles?.businesses?.name||"Service provider"}</Text><Text style={styles.offering}>{a.service_offerings?.name||"Appointment"}</Text><Text style={styles.date}>{new Date(a.starts_at).toLocaleString()}</Text><View style={styles.row}><Text style={styles.status}>{labels[a.status]||a.status}</Text><Text style={styles.payment}>{a.payment_status}</Text></View><Text style={styles.total}>{a.currency} {Number(a.price).toLocaleString()}</Text></Pressable>)}</ScrollView>}</SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},page:{padding:20,gap:16,paddingBottom:48},hero:{borderRadius:26,backgroundColor:colors.forest,padding:22,gap:7},kicker:{color:colors.goldSoft,fontSize:10,fontWeight:"800",letterSpacing:2,textTransform:"uppercase"},title:{color:colors.text,fontSize:30,fontWeight:"700"},body:{color:colors.textMuted,lineHeight:21},empty:{borderRadius:22,borderWidth:1,borderColor:colors.border,padding:20,gap:8},heading:{color:colors.text,fontSize:20,fontWeight:"700"},card:{borderRadius:22,borderWidth:1,borderColor:colors.border,backgroundColor:colors.bgCard,padding:18,gap:7},provider:{color:colors.text,fontSize:18,fontWeight:"800"},offering:{color:colors.goldSoft,fontWeight:"700"},date:{color:colors.textMuted},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderTopWidth:1,borderTopColor:colors.border,paddingTop:9,marginTop:3},status:{color:colors.gold,fontWeight:"800"},payment:{color:colors.textMuted,fontSize:12},total:{color:colors.text,fontSize:17,fontWeight:"800",alignSelf:"flex-end"}});