"use server";

import { supabaseAdmin } from "@/lib/supabase-admin";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth/require-admin";

const clean=(value:FormDataEntryValue|null)=>String(value||"").trim();
const refresh=(id:string)=>{revalidatePath(`/admin/ai-sales/edit/${id}`);revalidatePath("/admin/crm");};
const verificationStatuses=["unverified","verified","invalid"];

async function clearPrimaryContact(prospectId:string,exceptId?:string){let q=supabaseAdmin.from("crm_contacts").update({is_primary:false,updated_at:new Date().toISOString()}).eq("prospect_id",prospectId).eq("is_primary",true);if(exceptId)q=q.neq("id",exceptId);const {error}=await q;if(error)throw new Error(error.message);}

async function stablePartnerIdForProspect(prospectId:string){
  const [{data:suppliers,error:supplierError},{data:contacts,error:contactError}]=await Promise.all([
    supabaseAdmin.from("supplier_accounts").select("partner_id").eq("prospect_id",prospectId).not("partner_id","is",null),
    supabaseAdmin.from("crm_contacts").select("partner_id").eq("prospect_id",prospectId).not("partner_id","is",null),
  ]);
  if(supplierError)throw new Error(supplierError.message);
  if(contactError)throw new Error(contactError.message);
  const ids=new Set<string>();
  for(const row of suppliers||[])if(row.partner_id)ids.add(String(row.partner_id));
  for(const row of contacts||[])if(row.partner_id)ids.add(String(row.partner_id));
  if(ids.size>1)throw new Error("Conflicting stable partner links exist for this prospect. Resolve CRM linkage before continuing.");
  return ids.size===1?[...ids][0]:null;
}

async function persistStablePartnerLink(prospectId:string,partnerId:string){
  const [{error:contactError},{error:supplierError}]=await Promise.all([
    supabaseAdmin.from("crm_contacts").update({partner_id:partnerId,updated_at:new Date().toISOString()}).eq("prospect_id",prospectId).is("partner_id",null),
    supabaseAdmin.from("supplier_accounts").update({partner_id:partnerId,updated_at:new Date().toISOString()}).eq("prospect_id",prospectId).is("partner_id",null),
  ]);
  if(contactError)throw new Error(contactError.message);
  if(supplierError)throw new Error(supplierError.message);
}

export async function addCRMContact(prospectId:string,formData:FormData){await requireAdmin();const full_name=clean(formData.get("full_name"));if(!full_name)throw new Error("Contact name is required.");const is_primary=formData.get("is_primary")==="on";if(is_primary)await clearPrimaryContact(prospectId);const {data,error}=await supabaseAdmin.from("crm_contacts").insert({prospect_id:prospectId,full_name,job_title:clean(formData.get("job_title"))||null,email:clean(formData.get("email"))||null,phone:clean(formData.get("phone"))||null,linkedin_url:clean(formData.get("linkedin_url"))||null,source_url:clean(formData.get("source_url"))||null,notes:clean(formData.get("notes"))||null,is_primary}).select("id").single();if(error)throw new Error(error.message);await supabaseAdmin.from("crm_activities").insert({prospect_id:prospectId,contact_id:data.id,activity_type:"note",summary:`Contact added: ${full_name}`});refresh(prospectId);}

export async function updateCRMContact(prospectId:string,formData:FormData){await requireAdmin();const contactId=clean(formData.get("contact_id")),full_name=clean(formData.get("full_name"));if(!contactId||!full_name)throw new Error("Contact ID and name are required.");const is_primary=formData.get("is_primary")==="on";const requested=clean(formData.get("verification_status"));const verification_status=verificationStatuses.includes(requested)?requested:"unverified";if(is_primary)await clearPrimaryContact(prospectId,contactId);const {error}=await supabaseAdmin.from("crm_contacts").update({full_name,job_title:clean(formData.get("job_title"))||null,email:clean(formData.get("email"))||null,phone:clean(formData.get("phone"))||null,linkedin_url:clean(formData.get("linkedin_url"))||null,source_url:clean(formData.get("source_url"))||null,notes:clean(formData.get("notes"))||null,is_primary,verification_status,updated_at:new Date().toISOString()}).eq("id",contactId).eq("prospect_id",prospectId);if(error)throw new Error(error.message);await supabaseAdmin.from("crm_activities").insert({prospect_id:prospectId,contact_id:contactId,activity_type:"note",summary:`Contact updated: ${full_name}`,details:`Verification: ${verification_status}${is_primary?" · Primary contact":""}`});refresh(prospectId);}

export async function setPrimaryCRMContact(prospectId:string,formData:FormData){await requireAdmin();const contactId=clean(formData.get("contact_id"));if(!contactId)throw new Error("Contact ID is required.");await clearPrimaryContact(prospectId,contactId);const {data,error}=await supabaseAdmin.from("crm_contacts").update({is_primary:true,updated_at:new Date().toISOString()}).eq("id",contactId).eq("prospect_id",prospectId).select("full_name").single();if(error)throw new Error(error.message);await supabaseAdmin.from("crm_activities").insert({prospect_id:prospectId,contact_id:contactId,activity_type:"note",summary:`Primary contact set: ${data.full_name}`});refresh(prospectId);}

export async function addCRMActivity(prospectId:string,formData:FormData){await requireAdmin();const summary=clean(formData.get("summary"));if(!summary)throw new Error("Activity summary is required.");const allowed=["research","note","call","email","whatsapp","meeting","stage_change","approval","system"];const requested=clean(formData.get("activity_type"));const activity_type=allowed.includes(requested)?requested:"note";const {error}=await supabaseAdmin.from("crm_activities").insert({prospect_id:prospectId,activity_type,summary,details:clean(formData.get("details"))||null});if(error)throw new Error(error.message);refresh(prospectId);}
export async function addCRMFollowup(prospectId:string,formData:FormData){await requireAdmin();const title=clean(formData.get("title")),due=clean(formData.get("due_at"));if(!title||!due)throw new Error("Follow-up title and due date are required.");const due_at=new Date(due);if(Number.isNaN(due_at.getTime()))throw new Error("Follow-up due date is invalid.");const requested=clean(formData.get("priority")),priority=["low","normal","high"].includes(requested)?requested:"normal";const {error}=await supabaseAdmin.from("crm_followups").insert({prospect_id:prospectId,title,due_at:due_at.toISOString(),priority,notes:clean(formData.get("notes"))||null});if(error)throw new Error(error.message);await supabaseAdmin.from("crm_activities").insert({prospect_id:prospectId,activity_type:"system",summary:`Follow-up scheduled: ${title}`,details:`Due ${due_at.toISOString()}`});refresh(prospectId);}
export async function completeCRMFollowup(prospectId:string,formData:FormData){await requireAdmin();const followupId=clean(formData.get("followup_id"));if(!followupId)throw new Error("Follow-up ID is required.");const now=new Date().toISOString();const {data,error}=await supabaseAdmin.from("crm_followups").update({status:"completed",completed_at:now,updated_at:now}).eq("id",followupId).eq("prospect_id",prospectId).select("title").single();if(error)throw new Error(error.message);await supabaseAdmin.from("crm_activities").insert({prospect_id:prospectId,activity_type:"system",summary:`Follow-up completed: ${data.title}`});refresh(prospectId);}
export async function recordCRMConversion(prospectId:string,formData:FormData){await requireAdmin();const allowed=["qualified","meeting_booked","proposal_sent","partnered","lost","disqualified"];const outcome=clean(formData.get("outcome"));if(!allowed.includes(outcome))throw new Error("Invalid conversion outcome.");const notes=clean(formData.get("notes"))||null;const {data:prospect,error:prospectError}=await supabaseAdmin.from("ai_sales_prospects").select("id,status").eq("id",prospectId).single();if(prospectError||!prospect)throw new Error(prospectError?.message||"Prospect not found.");const partnerId=await stablePartnerIdForProspect(prospectId);const {error}=await supabaseAdmin.from("crm_conversions").insert({prospect_id:prospectId,partner_id:partnerId,outcome,source:"human",notes});if(error)throw new Error(error.message);const stageMap:Record<string,string>={qualified:"approved",meeting_booked:"contacted",proposal_sent:"pitch_sent",partnered:"partnered"};const nextStage=stageMap[outcome];if(nextStage){const {error:prospectStageError}=await supabaseAdmin.from("ai_sales_prospects").update({status:nextStage,updated_at:new Date().toISOString()}).eq("id",prospectId);if(prospectStageError)throw new Error(prospectStageError.message);if(partnerId){const partnerStage=outcome==="qualified"?"prospect":nextStage;const {error:partnerStageError}=await supabaseAdmin.from("safari_partners").update({outreach_stage:partnerStage}).eq("id",partnerId);if(partnerStageError)throw new Error(partnerStageError.message);}if(outcome==="partnered"){const now=new Date().toISOString();await supabaseAdmin.from("crm_followups").update({status:"completed",completed_at:now,updated_at:now}).eq("prospect_id",prospectId).eq("status","open");}}await supabaseAdmin.from("crm_activities").insert({prospect_id:prospectId,partner_id:partnerId,activity_type:"stage_change",summary:`Conversion outcome recorded: ${outcome.replaceAll("_"," ")}`,details:notes});refresh(prospectId);}
export async function approveSalesProspect(id:string){await requireAdmin();const {data:prospect,error:prospectError}=await supabaseAdmin.from("ai_sales_prospects").select("*").eq("id",id).single();if(prospectError||!prospect)throw new Error(prospectError?.message||"Sales prospect not found.");let partnerId=await stablePartnerIdForProspect(id);if(!partnerId){const {data:newPartner,error:partnerInsertError}=await supabaseAdmin.from("safari_partners").insert({venue_or_promoter_name:prospect.business_name,contact_person:null,email_or_phone:prospect.contact_email||prospect.phone||null,instagram_handle:prospect.instagram||null,outreach_stage:"prospect",notes:[prospect.description,prospect.website?`Website: ${prospect.website}`:null,prospect.facebook?`Facebook: ${prospect.facebook}`:null,prospect.source_name?`Source: ${prospect.source_name}`:null,prospect.source_url?`Source URL: ${prospect.source_url}`:null,prospect.notes||null].filter(Boolean).join("\n")}).select("id").single();if(partnerInsertError||!newPartner)throw new Error(`Partner CRM persistence failed: ${partnerInsertError?.message||"No relationship record returned"}`);partnerId=newPartner.id;}if(!partnerId)throw new Error("Stable partner ID could not be resolved.");const resolvedPartnerId=partnerId;await persistStablePartnerLink(id,resolvedPartnerId);const {error:prospectUpdateError}=await supabaseAdmin.from("ai_sales_prospects").update({status:"approved",review_status:"approved",updated_at:new Date().toISOString()}).eq("id",id);if(prospectUpdateError)throw new Error(prospectUpdateError.message);await supabaseAdmin.from("crm_activities").insert({prospect_id:id,partner_id:resolvedPartnerId,activity_type:"approval",summary:"Prospect approved for governed outreach",details:"Approval qualifies the prospect for outreach. It does not mark the business as partnered."});revalidatePath("/admin/ai-sales");revalidatePath("/admin/ai-sales/partners");revalidatePath("/admin/crm");redirect("/admin/ai-sales");}
export async function rejectSalesProspect(id:string){await requireAdmin();const {error}=await supabaseAdmin.from("ai_sales_prospects").update({status:"rejected",review_status:"rejected",updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);await supabaseAdmin.from("crm_activities").insert({prospect_id:id,activity_type:"approval",summary:"Prospect rejected"});revalidatePath("/admin/ai-sales");revalidatePath("/admin/crm");redirect("/admin/ai-sales");}
