import { NextRequest,NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { finalizeSupplierScout,pollSupplierScout,startSupplierScout,type SupplierScoutJob } from "@/app/admin/ai-sales/actions/supplier-scout-background";
export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=45;
async function authorized(r:NextRequest){const s=process.env.CRON_SECRET;if(s&&r.headers.get("authorization")===`Bearer ${s}`)return true;const token=r.headers.get("x-scout-worker-token");if(!token)return false;const {data,error}=await supabaseAdmin.rpc("verify_ai_scout_worker_token",{p_token:token});return !error&&data===true}
function job(v:unknown):SupplierScoutJob|null{const x=Array.isArray(v)?v[0]:v;if(!x||typeof x!=="object")return null;const r=x as SupplierScoutJob;return typeof r.id==="string"&&typeof r.city==="string"&&typeof r.category==="string"?r:null}
function nonRetryableProviderError(message:string){const value=message.toLowerCase();return value.includes("no credits remaining")||value.includes("insufficient_quota")||value.includes("billing")||value.includes("add credits")}async function fail(j:SupplierScoutJob,message:string){const nonRetryable=nonRetryableProviderError(message);const retry=!nonRetryable&&j.attempt_count<j.max_attempts;await supabaseAdmin.from("supplier_scout_jobs").update({status:retry?"queued":"failed",queued_at:retry?new Date().toISOString():undefined,claimed_at:null,provider_response_id:null,provider_status:null,completed_at:retry?null:new Date().toISOString(),last_error:(nonRetryable?"OpenAI API credits exhausted. Supplier Scout paused until API credits are available.":message).slice(0,1000)}).eq("id",j.id)}
function claimIsFresh(claimedAt:unknown){if(typeof claimedAt!=="string")return false;const claimed=Date.parse(claimedAt);return Number.isFinite(claimed)&&Date.now()-claimed<120000}
async function processRunning(running:Record<string,unknown>){const j=job(running);if(!j)throw new Error("Invalid Supplier Scout job");if(!running.provider_response_id){if(claimIsFresh(running.claimed_at))return NextResponse.json({ok:true,status:"starting",job_id:j.id},{status:202});await fail(j,"Running job is missing provider response id");return NextResponse.json({ok:true,requeued:j.id},{status:202})}const p=await pollSupplierScout(String(running.provider_response_id));if(p.status==="queued"||p.status==="in_progress"){await supabaseAdmin.from("supplier_scout_jobs").update({provider_status:p.status}).eq("id",j.id);return NextResponse.json({ok:true,status:p.status,job_id:j.id},{status:202})}if(p.status==="completed"&&p.outputText){const result=await finalizeSupplierScout(j,p.outputText);await supabaseAdmin.from("supplier_scout_jobs").update({status:"completed",provider_status:"completed",completed_at:new Date().toISOString(),claimed_at:null,qualified_count:result.qualified,contact_ready_count:result.contactReady,needs_research_count:result.needsResearch,inserted_count:result.inserted,last_error:null}).eq("id",j.id);return NextResponse.json({ok:true,status:"completed",job_id:j.id,...result})}await fail(j,p.error||`OpenAI ended with status ${p.status}`);return NextResponse.json({ok:true,status:"requeued",job_id:j.id},{status:202})}
export async function GET(request:NextRequest){if(!(await authorized(request)))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});try{const {data:recoverable,error:recoverError}=await supabaseAdmin.from("supplier_scout_jobs").select("*").eq("status","queued").not("provider_response_id","is",null).order("queued_at",{ascending:true}).limit(1).maybeSingle();if(recoverError)throw recoverError;if(recoverable){const {data:recovered,error}=await supabaseAdmin.from("supplier_scout_jobs").update({status:"running",claimed_at:new Date().toISOString(),last_error:null}).eq("id",recoverable.id).eq("status","queued").select("*").maybeSingle();if(error)throw error;if(recovered)return processRunning(recovered as Record<string,unknown>)}const {data:running,error:runningError}=await supabaseAdmin.from("supplier_scout_jobs").select("*").eq("status","running").order("claimed_at",{ascending:true}).limit(1).maybeSingle();if(runningError)throw runningError;if(running)return processRunning(running as Record<string,unknown>);const {data:claimed,error:claimError}=await supabaseAdmin.rpc("claim_next_supplier_scout_job");if(claimError)throw claimError;const j=job(claimed);if(!j)return NextResponse.json({ok:true,idle:true});try{const p=await startSupplierScout(j);const {data:saved,error:saveError}=await supabaseAdmin.from("supplier_scout_jobs").update({provider_response_id:p.id,provider_status:p.status||"queued"}).eq("id",j.id).eq("status","running").select("id").maybeSingle();if(saveError)throw saveError;if(!saved)throw new Error("Supplier Scout job lost its running lease while starting provider response");return NextResponse.json({ok:true,status:p.status||"queued",job_id:j.id},{status:202})}catch(e){await fail(j,e instanceof Error?e.message:"Could not start Supplier Scout");return NextResponse.json({ok:true,status:"requeued",job_id:j.id},{status:202})}}catch(e){console.error("SUPPLIER SCOUT WORKER ERROR",e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Supplier Scout worker failed"},{status:500})}}
