import Link from "next/link";
import { supabaseAdmin } from "@/lib/supabase-admin";
import {
  approveOutreach,
  markReadyToContact,
  markContacted,
  markFollowUpRequired,
  updateFollowUpDetails,
} from "./actions";


export default async function OutreachPage() {


  const { data: outreach } =
    await supabaseAdmin
      .from("ai_sales_outreach")
      .select(
`
id,
channel,
status,
approved,
created_at,
prospect_id,
response,
sent_at,
follow_up_date,
ai_sales_prospects (
    business_name,
    city,
    category,
    opportunity_score
  )
  `
)
      .order(
        "created_at",
        {
          ascending: false,
        }
      );



  const drafts =
    outreach?.filter(
      (item) =>
        item.status === "draft"
    ).length || 0;


  const approved =
    outreach?.filter(
      (item) =>
        item.approved === true
    ).length || 0;



  const sent =
    outreach?.filter(
      (item) =>
        item.status === "sent"
    ).length || 0;



  const replies =
    outreach?.filter(
      (item) =>
        item.response
    ).length || 0;



  return (

    <main className="min-h-screen bg-gray-50 p-8">

      <div className="mx-auto max-w-6xl">


        <Link
          href="/admin/ai-sales"
          className="text-blue-600"
        >
          ← Back to Sales
        </Link>



        <h1 className="mt-6 text-3xl font-bold">
          SafariPlug AI Outreach Pipeline
        </h1>


        <p className="mt-2 text-gray-600">
          Manage partnership communication generated by AI Sales Agent.
        </p>



        <div className="mt-8 grid gap-4 md:grid-cols-4">


          {[
            ["Drafts", drafts],
            ["Approved", approved],
            ["Sent", sent],
            ["Replies", replies],
          ].map(
            ([label, value]) => (

              <div
                key={label}
                className="rounded-xl bg-white p-6 shadow"
              >

                <p className="text-gray-500">
                  {label}
                </p>

                <p className="text-3xl font-bold">
                  {value}
                </p>

              </div>

            )
          )}


        </div>



        <div className="mt-8 rounded-xl bg-white p-6 shadow">


          <h2 className="text-xl font-bold">
            Outreach Queue
          </h2>



          <div className="mt-6 space-y-4">


          {outreach?.map(
            (item:any) => (

              <div
                key={item.id}
                className="rounded-xl border p-5"
              >

                <h3 className="text-lg font-bold">
                  {item.ai_sales_prospects?.business_name}
                </h3>


                <p className="text-gray-600">
                  {item.ai_sales_prospects?.city}
                  {" · "}
                  {item.ai_sales_prospects?.category}
                </p>


                <p className="mt-2">
                  Score:
                  {" "}
                  <b>
                    {item.ai_sales_prospects?.opportunity_score}%
                  </b>
                </p>


                <p className="mt-2">
                  Channel:
                  {" "}
                  {item.channel}
                </p>


                <p>
                  Status:
                  {" "}
                  {item.status}
                </p>

<div className="mt-4 flex gap-3">

  {item.status === "approved" && (

    <form action={markReadyToContact}>

      <input
        type="hidden"
        name="id"
        value={item.id}
      />

      <button
        className="rounded-xl bg-black px-4 py-2 text-white"
      >
        Mark Ready To Contact
      </button>

    </form>

  )}
{item.status === "ready_to_contact" && (

<form action={markContacted}>

<input
type="hidden"
name="id"
value={item.id}
/>

<button
className="rounded-xl bg-blue-600 px-4 py-2 text-white"
>
Mark Contacted
</button>

</form>

)}
{item.status === "contacted" && (

<form action={markFollowUpRequired}>

<input
type="hidden"
name="id"
value={item.id}
/>

<button
className="rounded-xl bg-purple-600 px-4 py-2 text-white"
>
Schedule Follow Up
</button>

</form>

)}


{item.status === "follow_up_required" && (

<form
action={updateFollowUpDetails}
className="mt-4 space-y-3"
>

<input
type="hidden"
name="id"
value={item.id}
/>


<textarea
name="follow_up_notes"
placeholder="Add follow up notes..."
className="w-full rounded-xl border p-3"
/>


<select
name="outcome"
className="w-full rounded-xl border p-3"
>

<option value="">
Select outcome
</option>

<option value="interested">
Interested
</option>

<option value="no_response">
No response
</option>

<option value="not_interested">
Not interested
</option>

<option value="callback">
Call back later
</option>

<option value="confirmed">
Partnership confirmed
</option>

</select>


<button
className="rounded-xl bg-green-600 px-4 py-2 text-white"
>
Save Follow Up
</button>


</form>

)}
</div>
{!item.approved && (

<form action={approveOutreach} className="mt-4">

<input
  type="hidden"
  name="id"
  value={item.id}
/>

<button
  className="rounded-lg bg-black px-4 py-2 text-white"
>
  Approve Outreach
</button>

</form>

)}


              </div>

            )
          )}


          </div>


        </div>


      </div>


    </main>

  );

}