import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router, Stack, useLocalSearchParams } from "expo-router";
import { apiGet, apiPost } from "../../src/api/client";
import { supabase } from "../../src/auth";
import { API_BASE_URL } from "../../src/config";
import { ErrorBlock, LoadingBlock } from "../../src/components/StatusBlocks";
import { colors } from "../../src/theme";

type Offering={id:string;name:string;description?:string|null;duration_minutes:number;price:number;currency:string;requires_confirmation?:boolean};
type Service={id:string;timezone:string;businesses:{name:string;description?:string|null;city_id?:string|null};service_categories:{name:string;slug:string};service_offerings:Offering[]};
type Slot={staffId:string;staffName:string;startsAt:string;endsAt:string;label:string};

export default function ServiceScreen(){
 const {serviceProfileId,name}=useLocalSearchParams<{serviceProfileId:string;name?:string}>();
 const [service,setService]=useState<Service|null>(null); const [offering,setOffering]=useState<Offering|null>(null); const [date,setDate]=useState(()=>new Date(Date.now()+86400000).toISOString().slice(0,10)); const [slots,setSlots]=useState<Slot[]>([]); const [selected,setSelected]=useState<Slot|null>(null); const [customer,setCustomer]=useState({name:"",phone:"",email:"",notes:""}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!serviceProfileId)return;setLoading(true);setMessage(null);try{const r=await apiGet<Service[]>("/services/bookable");const found=r.data.find(x=>x.id===serviceProfileId);if(!found)throw new Error("Service is no longer bookable.");setService(found);setOffering(current=>current&&found.service_offerings.some(x=>x.id===current.id)?current:found.service_offerings[0]||null);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load this service.")}finally{setLoading(false)}},[serviceProfileId]);
 useEffect(()=>{void load()},[load]);
 const loadSlots=useCallback(async()=>{if(!service||!offering)return;setMessage(null);try{const r=await fetch(`${API_BASE_URL}/api/services/availability?serviceProfileId=${encodeURIComponent(service.id)}&offeringId=${encodeURIComponent(offering.id)}&date=${encodeURIComponent(date)}`);const b=await r.json();if(!r.ok)throw new Error(b?.error||"Unable to load live availability.");setSlots(Array.isArray(b.slots)?b.slots:[]);setSelected(null);}catch(e){setSlots([]);setMessage(e instanceof Error?e.message:"Unable to load live availability.")}},[service,offering,date]);
 useEffect(()=>{void loadSlots()},[loadSlots]);
 const selectedDate=new Date(`${date}T00:00:00Z`); const dateLabel=selectedDate.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});
 async function book(){if(!service||!offering||!selected)return;setMessage(null);const{data}=await supabase.auth.getSession();if(!data.session){setMessage("Sign in to book an appointment.");return}if(!customer.name.trim()||!customer.phone.trim()){setMessage("Add your name and phone number.");return}setBusy(true);try{const r=await apiPost<unknown>("/services/book",{serviceProfileId:service.id,offeringId:offering.id,staffId:selected.staffId,startsAt:selected.startsAt,customerName:customer.name.trim(),customerPhone:customer.phone.trim(),customerEmail:customer.email.trim()||undefined,customerNotes:customer.notes.trim()||undefined},true);router.replace({pathname:"/appointment/[appointmentId]",params:{appointmentId:(r.data as any).id}})}catch(e){setMessage(e instanceof Error?e.message:"Unable to book this appointment.")}finally{setBusy(false)}}
 const canBackDate=useMemo(()=>true,[]);
 if(loading)return<SafeAreaView style={styles.safe}><LoadingBlock label="Loading service…"/></SafeAreaView>;
 if(!service)return<SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><ErrorBlock message={message||"Service unavailable."} onRetry={()=>void load()}/></ScrollView></SafeAreaView>;
 return <SafeAreaView style={styles.safe} edges={["top"]}><Stack.Screen options={{title:typeof name==="string"?name:service.businesses.name}}/><ScrollView contentContainerStyle={styles.page}>
  <View style={styles.hero}><Text style={styles.kicker}>{service.service_categories?.name||"SafariPlug Service"}</Text><Text style={styles.title}>{service.businesses.name}</Text><Text style={styles.body}>{service.businesses.description||"Discover a verified local specialist with live appointment availability."}</Text></View>
  <View style={styles.section}><Text style={styles.sectionTitle}>Choose a service</Text>{service.service_offerings.map(item=><Pressable key={item.id} onPress={()=>setOffering(item)} style={[styles.optionCard,offering?.id===item.id&&styles.optionActive]}><View style={{flex:1}}><Text style={styles.optionTitle}>{item.name}</Text>{item.description?<Text style={styles.body}>{item.description}</Text>:null}<Text style={styles.price}>{item.currency} {Number(item.price).toLocaleString()} · {item.duration_minutes} min</Text></View><Text style={styles.radio}>{offering?.id===item.id?"●":"○"}</Text></Pressable>)}</View>
  <View style={styles.section}><Text style={styles.sectionTitle}>Choose a date</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.textMuted} style={styles.input}/><Text style={styles.body}>Showing live availability for {dateLabel}.</Text><View style={styles.slots}>{slots.length?slots.map(slot=><Pressable key={`${slot.staffId}-${slot.startsAt}`} onPress={()=>setSelected(slot)} style={[styles.slot,selected?.startsAt===slot.startsAt&&selected?.staffId===slot.staffId&&styles.slotActive]}><Text style={styles.slotTime}>{slot.label}</Text><Text style={styles.slotStaff}>{slot.staffName}</Text></Pressable>):<Text style={styles.body}>No live slots for this date. Try another date.</Text>}</View></View>
  <View style={styles.section}><Text style={styles.sectionTitle}>Your details</Text><TextInput value={customer.name} onChangeText={v=>setCustomer(c=>({...c,name:v}))} placeholder="Full name" placeholderTextColor={colors.textMuted} style={styles.input}/><TextInput value={customer.phone} onChangeText={v=>setCustomer(c=>({...c,phone:v}))} placeholder="Phone number" placeholderTextColor={colors.textMuted} keyboardType="phone-pad" style={styles.input}/><TextInput value={customer.email} onChangeText={v=>setCustomer(c=>({...c,email:v}))} placeholder="Email (optional)" placeholderTextColor={colors.textMuted} keyboardType="email-address" autoCapitalize="none" style={styles.input}/><TextInput value={customer.notes} onChangeText={v=>setCustomer(c=>({...c,notes:v}))} placeholder="Notes (optional)" placeholderTextColor={colors.textMuted} style={[styles.input,styles.multiline]} multiline/>{message?<Text style={styles.message}>{message}</Text>:null}<Pressable disabled={!selected||busy} onPress={()=>void book()} style={[styles.button,(!selected||busy)&&styles.disabled]}><Text style={styles.buttonText}>{busy?"Booking…":"Book appointment"}</Text></Pressable><Text style={styles.body}>SafariPlug re-checks provider status, staff eligibility, availability and booking windows on the server.</Text></View>
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},page:{padding:20,gap:16,paddingBottom:56},hero:{borderRadius:26,backgroundColor:colors.forest,padding:22,gap:7},kicker:{color:colors.goldSoft,fontSize:10,fontWeight:"800",letterSpacing:2,textTransform:"uppercase"},title:{color:colors.text,fontSize:30,fontWeight:"700"},body:{color:colors.textMuted,lineHeight:20},section:{gap:10},sectionTitle:{color:colors.text,fontSize:22,fontWeight:"700"},optionCard:{flexDirection:"row",alignItems:"center",borderRadius:18,borderWidth:1,borderColor:colors.border,backgroundColor:colors.bgCard,padding:16,gap:10},optionActive:{borderColor:colors.gold,backgroundColor:colors.forest},optionTitle:{color:colors.text,fontSize:17,fontWeight:"700"},price:{color:colors.goldSoft,fontWeight:"800",marginTop:5},radio:{color:colors.gold,fontSize:20},input:{borderWidth:1,borderColor:colors.border,borderRadius:14,backgroundColor:colors.bgCard,color:colors.text,paddingHorizontal:14,paddingVertical:12},multiline:{minHeight:80,textAlignVertical:"top"},slots:{flexDirection:"row",flexWrap:"wrap",gap:8},slot:{minWidth:100,borderRadius:14,borderWidth:1,borderColor:colors.border,padding:12,backgroundColor:colors.bgCard},slotActive:{borderColor:colors.gold,backgroundColor:colors.forest},slotTime:{color:colors.text,fontWeight:"800"},slotStaff:{color:colors.textMuted,fontSize:11,marginTop:3},message:{color:colors.goldSoft,fontWeight:"700"},button:{borderRadius:16,backgroundColor:colors.gold,paddingVertical:15,alignItems:"center"},disabled:{opacity:.5},buttonText:{color:colors.bg,fontWeight:"900"}});