import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { LockTripHotelAdapter } from "@/lib/integrations/hotels/locktrip";
import { convertCurrency } from "@/lib/currency/exchange-rates";
import { getPaymentAdapter } from "@/lib/payments/registry";

export const dynamic = "force-dynamic";
const RETAIL_MARKUP_PERCENT = 10;
const DEFAULT_CUSTOMER_CURRENCY = "KES";
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://www.safariplug.com").replace(/\/$/, "");
const LOCKTRIP_BASE_URL = (process.env.SAFARIPLUG_HOTEL_LOCKTRIP_BASE_URL || "https://locktrip.com/mcp/tools").replace(/\/$/, "");
function errorResponse(status: number, message: string) { return NextResponse.json({ error: "locktrip_error", message }, { status }); }
function retailAmount(net: number) { return Math.round(net * (1 + RETAIL_MARKUP_PERCENT / 100) * 100) / 100; }
async function requireUser() { const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); return user; }
function getConfiguredCredentials() { const email = process.env.SAFARIPLUG_HOTEL_LOCKTRIP_EMAIL?.trim(); const password = process.env.SAFARIPLUG_HOTEL_LOCKTRIP_PASSWORD?.trim(); return email && password ? { email, password } : null; }
async function getRegisteredLockTripToken() { const credentials = getConfiguredCredentials(); if (!credentials) throw new Error("SafariPlug hotel booking is awaiting its registered LockTrip account credentials."); const result = await fetch(`${LOCKTRIP_BASE_URL}/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(credentials), cache: "no-store" }); if (!result.ok) throw new Error("LockTrip account authentication failed."); const data = await result.json() as { token?: string }; if (!data.token) throw new Error("LockTrip did not return an authentication token."); return data.token; }
async function getLockTripBookingToken(adapter: LockTripHotelAdapter, email: string) { const credentials = getConfiguredCredentials(); if (credentials) return getRegisteredLockTripToken(); return adapter.guestLogin(email); }
async function attachConfirmedHotelToTrip(params: { supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>; userId: string; tripId: string; ledgerId: string; hotelName: string; checkIn: string | null; checkOut: string | null; providerReference: string | null; cityId?: string | null }) { const { supabase, userId, tripId, ledgerId, hotelName, checkIn, checkOut, providerReference, cityId } = params; const { data: trip } = await supabase.from("trips").select("id").eq("id", tripId).eq("traveler_id", userId).maybeSingle(); if (!trip) throw new Error("Trip not found."); const marker = `SafariPlug hotel ledger: ${ledgerId}`; const { data: existing } = await supabase.from("trip_items").select("id,trip_id,item_kind,position,start_at,end_at,title,notes,city_id").eq("trip_id", tripId).eq("item_kind", "hotel").ilike("notes", `%${ledgerId}%`).maybeSingle(); if (existing) return existing; const { count } = await supabase.from("trip_items").select("id", { count: "exact", head: true }).eq("trip_id", tripId); const notes = [marker, providerReference ? `LockTrip reference: ${providerReference}` : null].filter(Boolean).join("\n"); const { data, error } = await supabase.from("trip_items").insert({ trip_id: tripId, item_kind: "hotel", booking_id: null, position: count ?? 0, start_at: checkIn, end_at: checkOut, title: hotelName, city_id: cityId || null, notes }).select("id,trip_id,item_kind,position,start_at,end_at,title,notes,city_id").single(); if (error) throw new Error(`Hotel booking confirmed, but itinerary attachment failed: ${error.message}`); return data; }
export async function POST(request: Request) {
  const user = await requireUser(); if (!user) return errorResponse(401, "Authentication required.");
  let body: Record<string, unknown>; try { body = await request.json(); } catch { return errorResponse(400, "Invalid JSON body."); }
  const action = String(body.action || ""); const adapter = new LockTripHotelAdapter();
  try {
    if (action === "rooms") { const hotelId = String(body.hotelId || ""), searchKey = String(body.searchKey || ""), regionId = String(body.regionId || ""), checkIn = String(body.checkIn || ""), checkOut = String(body.checkOut || ""), rooms = Array.isArray(body.rooms) ? body.rooms : []; if (!hotelId || !searchKey || !regionId || !checkIn || !checkOut || rooms.length === 0) return errorResponse(400, "hotelId, searchKey, regionId, checkIn, checkOut and rooms are required."); const data = await adapter.getRooms({ hotelId, searchKey, regionId, checkIn, checkOut, rooms: rooms as Array<{ adults: number; childrenAges?: number[] }>, currency: typeof body.currency === "string" ? body.currency : DEFAULT_CUSTOMER_CURRENCY }); return NextResponse.json({ provider: "locktrip", ...data }); }
    if (action === "prepare") {
      const email = user.email || String(body.email || ""); if (!email) return errorResponse(400, "A customer email is required."); const quoteId = String(body.quoteId || ""), searchKey = String(body.searchKey || ""); if (!quoteId || !searchKey) return errorResponse(400, "quoteId and searchKey are required."); const customerCurrency = String(body.currency || DEFAULT_CUSTOMER_CURRENCY).toUpperCase(); if (customerCurrency !== "KES") return errorResponse(400, "Hotel M-Pesa checkout currently supports KES only.");
      const token = await getLockTripBookingToken(adapter, email); const booking = await adapter.prepareBooking(token, { quoteId, searchKey, rooms: body.rooms, contactPerson: body.contactPerson, specialRequests: typeof body.specialRequests === "string" ? body.specialRequests : undefined }); const supplierCurrency = String(booking.currency || "USD").toUpperCase(); const supplierNetAmount = Number(booking.price); if (!Number.isFinite(supplierNetAmount) || supplierNetAmount < 0) return errorResponse(502, "LockTrip returned an invalid booking price."); const supplierRetailAmount = retailAmount(supplierNetAmount); const converted = await convertCurrency(supplierRetailAmount, supplierCurrency, customerCurrency); const supabase = await createSupabaseServerClient(); const tripId = typeof body.tripId === "string" && body.tripId ? body.tripId : null;
      const { data: ledger, error: ledgerError } = await supabase.from("hotel_booking_pricing_ledger").insert({ customer_user_id: user.id, provider: "locktrip", quote_id: quoteId, prepared_booking_id: booking.preparedBookingId, currency: customerCurrency, supplier_currency: supplierCurrency, customer_currency: customerCurrency, exchange_rate: converted.rate, supplier_net_amount: supplierNetAmount, retail_amount: supplierRetailAmount, customer_retail_amount: converted.amount, markup_percent: RETAIL_MARKUP_PERCENT, payment_status: "unpaid", booking_status: "payment_pending", supplier_settlement_status: "pending", metadata: { searchKey, hotelId: body.hotelId ?? null, checkIn: body.checkIn ?? null, checkOut: body.checkOut ?? null, tripId, bookingInternalId: booking.bookingInternalId || booking.preparedBookingId } }).select("id, supplier_net_amount, retail_amount, customer_retail_amount, supplier_currency, customer_currency, exchange_rate, currency, markup_percent, payment_status, booking_status").single(); if (ledgerError || !ledger) throw new Error("Unable to create hotel pricing ledger entry.");
      const method = String(body.method || "mpesa").toLowerCase(); if (method !== "mpesa") return errorResponse(409, "Hotel customer payment must use SafariPlug M-Pesa checkout."); const mpesa = getPaymentAdapter("mpesa"); if (!mpesa) return errorResponse(503, "M-Pesa is not configured yet."); const customerPhone = typeof body.customerPhone === "string" ? body.customerPhone : null; if (!customerPhone) return errorResponse(400, "A customer M-Pesa phone number is required.");
      const payment = await mpesa.createPaymentIntent({ appointmentId: ledger.id, amount: converted.amount, currency: customerCurrency, customerEmail: user.email, customerPhone, returnUrl: `${SITE_URL}/hotels/booking-result?bookingId=${encodeURIComponent(booking.preparedBookingId)}`, idempotencyKey: `hotel:${ledger.id}`, callbackUrl: `${SITE_URL}/api/v1/hotels/locktrip/mpesa/callback` }); await supabase.from("hotel_booking_pricing_ledger").update({ payment_provider: "mpesa", payment_reference: payment.providerReference, payment_status: "pending", metadata: { searchKey, hotelId: body.hotelId ?? null, checkIn: body.checkIn ?? null, checkOut: body.checkOut ?? null, tripId, bookingInternalId: booking.bookingInternalId || booking.preparedBookingId, mpesaPaymentId: payment.id } }).eq("id", ledger.id);
      return NextResponse.json({ provider: "locktrip", booking, pricing: { supplierNetAmount, supplierRetailAmount, customerRetailAmount: converted.amount, markupPercent: RETAIL_MARKUP_PERCENT, supplierCurrency, customerCurrency, exchangeRate: converted.rate }, ledger: { ...ledger, payment_provider: "mpesa", payment_reference: payment.providerReference, payment_status: "pending" }, payment });
    }
    if (action === "payment_status") { const preparedBookingId = String(body.preparedBookingId || ""); if (!preparedBookingId) return errorResponse(400, "preparedBookingId is required."); const supabase = await createSupabaseServerClient(); const { data: ledger, error } = await supabase.from("hotel_booking_pricing_ledger").select("*").eq("customer_user_id", user.id).eq("prepared_booking_id", preparedBookingId).maybeSingle(); if (error) throw new Error(error.message); if (!ledger) return errorResponse(404, "Hotel booking not found."); if (ledger.payment_provider !== "mpesa" || !ledger.payment_reference) return errorResponse(409, "This hotel booking does not have an M-Pesa payment reference."); const mpesa = getPaymentAdapter("mpesa"); if (!mpesa) return errorResponse(503, "M-Pesa is not configured yet."); const status = await mpesa.getPaymentStatus(ledger.payment_reference); const updates: Record<string, unknown> = { payment_status: status === "succeeded" ? "paid" : status === "failed" ? "failed" : "pending", metadata: { ...(ledger.metadata || {}), lastMpesaStatus: status } }; if (status === "succeeded") updates.paid_at = new Date().toISOString(); const { data: updatedLedger, error: updateError } = await supabase.from("hotel_booking_pricing_ledger").update(updates).eq("id", ledger.id).select("*").single(); if (updateError) throw new Error(updateError.message); return NextResponse.json({ provider: "mpesa", status, ledger: updatedLedger }); }
    if (action === "status") {
      const preparedBookingId = String(body.preparedBookingId || ""); if (!preparedBookingId) return errorResponse(400, "preparedBookingId is required."); const supabase = await createSupabaseServerClient(); const { data: ledger, error: ledgerError } = await supabase.from("hotel_booking_pricing_ledger").select("*").eq("customer_user_id", user.id).eq("prepared_booking_id", preparedBookingId).maybeSingle(); if (ledgerError) throw new Error(ledgerError.message); if (!ledger) return errorResponse(404, "Hotel booking not found.");
      let workingLedger = ledger;
      if (workingLedger.payment_provider === "mpesa" && workingLedger.payment_reference && workingLedger.payment_status !== "paid") { const mpesa = getPaymentAdapter("mpesa"); if (mpesa) { const mpesaStatus = await mpesa.getPaymentStatus(workingLedger.payment_reference); if (mpesaStatus === "succeeded") { const { data: refreshed } = await supabase.from("hotel_booking_pricing_ledger").update({ payment_status: "paid", paid_at: new Date().toISOString(), metadata: { ...(workingLedger.metadata || {}), lastMpesaStatus: mpesaStatus } }).eq("id", workingLedger.id).select("*").single(); if (refreshed) workingLedger = refreshed; } } }
      if (workingLedger.payment_status !== "paid") return NextResponse.json({ provider: "mpesa", status: "payment_pending", ledger: workingLedger, supplierStatus: "awaiting_customer_payment" });
      if (!getConfiguredCredentials()) return NextResponse.json({ provider: "locktrip", status: "payment_pending", reconciliation: "awaiting_registered_provider_account", message: "Customer payment is recorded, but supplier confirmation requires SafariPlug's registered LockTrip account.", ledger: workingLedger });
      const token = await getRegisteredLockTripToken();
      const metadata = workingLedger.metadata && typeof workingLedger.metadata === "object" && !Array.isArray(workingLedger.metadata) ? workingLedger.metadata as Record<string, unknown> : {};
      const details = await adapter.getBookingDetails(token, preparedBookingId); const providerStatus = String(details.status || "").toUpperCase(), paymentStatus = String(details.paymentStatus || "").toUpperCase();
      const confirmed = providerStatus === "DONE" && paymentStatus === "PAID", cancelled = providerStatus === "CANCELLED", failed = cancelled || providerStatus === "FAILED";
      if (confirmed || failed) {
        const updates: Record<string, unknown> = { metadata: { ...metadata, lastProviderStatus: details } };
        if (confirmed) { updates.payment_status = "paid"; updates.booking_status = "confirmed"; updates.supplier_settlement_status = "settled"; updates.provider_booking_reference = details.bookingReferenceId || null; updates.paid_at = details.confirmedAt || workingLedger.paid_at || new Date().toISOString(); updates.confirmed_at = details.confirmedAt || new Date().toISOString(); }
        else { updates.booking_status = cancelled ? "cancelled" : "failed"; updates.supplier_settlement_status = "failed"; }
        const { data: updatedLedger, error: updateError } = await supabase.from("hotel_booking_pricing_ledger").update(updates).eq("id", workingLedger.id).eq("customer_user_id", user.id).select("*").single(); if (updateError) throw new Error(updateError.message);
        const storedTripId = typeof metadata.tripId === "string" ? metadata.tripId : null, tripId = typeof body.tripId === "string" && body.tripId ? body.tripId : storedTripId; let itineraryItem = null; if (confirmed && tripId) itineraryItem = await attachConfirmedHotelToTrip({ supabase, userId: user.id, tripId, ledgerId: workingLedger.id, hotelName: details.hotel?.name || "Hotel stay", checkIn: details.checkIn || null, checkOut: details.checkOut || null, providerReference: details.bookingReferenceId || null, cityId: null });
        return NextResponse.json({ provider: "locktrip", status: confirmed ? "confirmed" : String(updates.booking_status), providerBooking: details, ledger: updatedLedger, itineraryItem });
      }
      const alreadyAccepted = typeof metadata.confirmAcceptedAt === "string";
      const alreadyIndeterminate = typeof metadata.confirmAttemptIndeterminateAt === "string";
      const alreadyRefused = typeof metadata.confirmRefusedAt === "string";
      if (!alreadyAccepted && !alreadyIndeterminate && !alreadyRefused) {
        const bookingInternalId = typeof metadata.bookingInternalId === "string" && metadata.bookingInternalId ? metadata.bookingInternalId : preparedBookingId;
        const confirmation = await adapter.confirmBooking(token, { bookingInternalId, quoteId: workingLedger.quote_id });
        const confirmationMetadata = { ...metadata, confirmResponse: confirmation, lastProviderStatus: details };
        if (confirmation.serviceUnavailable) {
          const { data: pendingLedger, error: pendingError } = await supabase.from("hotel_booking_pricing_ledger").update({ booking_status: "payment_pending", supplier_settlement_status: "pending", metadata: { ...confirmationMetadata, confirmAttemptIndeterminateAt: new Date().toISOString() } }).eq("id", workingLedger.id).eq("customer_user_id", user.id).select("*").single(); if (pendingError) throw new Error(pendingError.message);
          return NextResponse.json({ provider: "locktrip", status: "payment_pending", supplierStatus: "confirmation_indeterminate", message: confirmation.message || "LockTrip did not confirm the credit-line request. The booking will be re-checked before any retry.", providerBooking: details, ledger: pendingLedger });
        }
        if (confirmation.accepted === false) {
          const { data: refusedLedger, error: refusedError } = await supabase.from("hotel_booking_pricing_ledger").update({ booking_status: "payment_pending", supplier_settlement_status: "failed", metadata: { ...confirmationMetadata, confirmRefusedAt: new Date().toISOString() } }).eq("id", workingLedger.id).eq("customer_user_id", user.id).select("*").single(); if (refusedError) throw new Error(refusedError.message);
          return NextResponse.json({ provider: "locktrip", status: "payment_pending", supplierStatus: "credit_line_refused", message: confirmation.message || "LockTrip refused supplier confirmation. Customer payment remains recorded; no automatic retry will be attempted.", providerBooking: details, ledger: refusedLedger });
        }
        if (confirmation.accepted === true) {
          const { data: acceptedLedger, error: acceptedError } = await supabase.from("hotel_booking_pricing_ledger").update({ booking_status: "payment_pending", supplier_settlement_status: "pending", metadata: { ...confirmationMetadata, confirmAcceptedAt: new Date().toISOString(), voucherUrl: confirmation.voucherUrl || null } }).eq("id", workingLedger.id).eq("customer_user_id", user.id).select("*").single(); if (acceptedError) throw new Error(acceptedError.message);
          workingLedger = acceptedLedger || workingLedger;
        }
      }
      const refreshedDetails = await adapter.getBookingDetails(token, preparedBookingId); const refreshedStatus = String(refreshedDetails.status || "").toUpperCase(), refreshedPaymentStatus = String(refreshedDetails.paymentStatus || "").toUpperCase(); const refreshedConfirmed = refreshedStatus === "DONE" && refreshedPaymentStatus === "PAID";
      const latestMetadata = workingLedger.metadata && typeof workingLedger.metadata === "object" && !Array.isArray(workingLedger.metadata) ? workingLedger.metadata as Record<string, unknown> : metadata;
      const finalUpdates: Record<string, unknown> = { metadata: { ...latestMetadata, lastProviderStatus: refreshedDetails } };
      if (refreshedConfirmed) { finalUpdates.payment_status = "paid"; finalUpdates.booking_status = "confirmed"; finalUpdates.supplier_settlement_status = "settled"; finalUpdates.provider_booking_reference = refreshedDetails.bookingReferenceId || null; finalUpdates.paid_at = refreshedDetails.confirmedAt || workingLedger.paid_at || new Date().toISOString(); finalUpdates.confirmed_at = refreshedDetails.confirmedAt || new Date().toISOString(); }
      const { data: finalLedger, error: finalError } = await supabase.from("hotel_booking_pricing_ledger").update(finalUpdates).eq("id", workingLedger.id).eq("customer_user_id", user.id).select("*").single(); if (finalError) throw new Error(finalError.message);
      const storedTripId = typeof latestMetadata.tripId === "string" ? latestMetadata.tripId : null, tripId = typeof body.tripId === "string" && body.tripId ? body.tripId : storedTripId; let itineraryItem = null; if (refreshedConfirmed && tripId) itineraryItem = await attachConfirmedHotelToTrip({ supabase, userId: user.id, tripId, ledgerId: workingLedger.id, hotelName: refreshedDetails.hotel?.name || "Hotel stay", checkIn: refreshedDetails.checkIn || null, checkOut: refreshedDetails.checkOut || null, providerReference: refreshedDetails.bookingReferenceId || null, cityId: null });
      return NextResponse.json({ provider: "locktrip", status: refreshedConfirmed ? "confirmed" : "payment_pending", supplierStatus: refreshedConfirmed ? "settled" : alreadyAccepted ? "confirmation_accepted_awaiting_supplier" : alreadyIndeterminate ? "confirmation_pending_recheck" : alreadyRefused ? "credit_line_refused" : "confirmation_pending", providerBooking: refreshedDetails, ledger: finalLedger, itineraryItem });
    }
    return errorResponse(400, "Unsupported LockTrip action.");
  } catch (error) { return errorResponse(502, error instanceof Error ? error.message : "LockTrip request failed."); }
}
