"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Partner={id:string;venue_or_promoter_name:string;contact_person:string|null;email_or_phone:string|null;outreach_stage:string};
type Invitation={id:string;business_name:string;partner_type:string;status:string;contact_email:string|null;whatsapp_phone:string|null};
type Supplier={id:string;contact_name:string;invitation_status:string;onboarding_status:string;completion_percent:number;submitted_at:string|null;approved_at:string|null;businesses:{id:string;name:string;email:string|null;phone:string|null;status:string}|null};
type CRMData={partners:Partner[];invitations:Invitation[];suppliers:Supplier[]};

export default function PartnerCRMPage(){
 const [data,setData]=useState<CRMData>({partners:[],invitations:[],suppliers:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");const response=await fetch("/api/admin/partner-crm",{cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)setError(payload?.error||"Unable to load Partner CRM.");else setData({partners:payload?.partners||[],invitations:payload?.invitations||[],suppliers:payload?.suppliers||[]});setLoading(false)}
 useEffect(()=>{void load()},[]);
 const metrics=useMemo(()=>({prospects:data.partners.filter(p=>p.outreach_stage==="prospect").length,inviteAction:data.invitations.filter(i=>["draft","ready_for_approval","approved"].includes(i.status)).length,opened:data.invitations.filter(i=>i.status==="opened").length,signup:data.invitations.filter(i=>i.status==="signup_started").length,onboarding:data.suppliers.filter(s=>["invited","in_progress","changes_requested"].includes(s.onboarding_status)).length,review:data.suppliers.filter(s=>s.onboarding_status==="submitted").length,active:data.suppliers.filter(s=>["approved","live"].includes(s.onboarding_status)).length}),[data]);
 const attention=[...data.invitations.filter(i=>["draft","ready_for_approval","approved","opened","signup_started"].includes(i.status)).map(i=>({id:`i-${i.id}`,name:i.business_name,status:i.status,detail:`${i.partner_type} · ${i.contact_email||i.whatsapp_phone||"contact pending"}`,href:"/admin/ai-sales/invitations",action:["draft","ready_for_approval","approved"].includes(i.status)?"Review invitation":"Check enrollment"})),...data.suppliers.filter(s=>["in_progress","changes_requested","submitted"].includes(s.onboarding_status)).map(s=>({id:`s-${s.id}`,name:s.businesses?.name||s.contact_name,status:s.onboarding_status,detail:`${s.completion_percent||0}% onboarding complete`,href:`/admin/ai-sales/partners/${s.id}`,action:s.onboarding_status==="submitted"?"Review Partner 360":"Open Partner 360"}))].slice(0,12);
 return <main className="min-h-screen bg-[#070707] p-5 text-white md:p-10"><div className="mx-auto max-w-7xl">
  <header className="border-b border-zinc-800 pb-7"><p className="font-mono text-[11px] font-bold uppercase tracking-[.22em] text-amber-400">SafariPlug // Partner Growth Command Center</p><div className="mt-2 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><h1 className="text-3xl font-bold md:text-4xl">Partner CRM</h1><p className="mt-2 max-w-2xl text-sm text-zinc-400">Discover → Invite → Onboard → Verify → Activate → Manage. The operating view for SafariPlug supply growth.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/ai-sales" className="rounded-xl border border-zinc-700 px-4 py-2 text-sm">Find Partners with AI</Link><Link href="/admin/ai-sales/invitations" className="rounded-xl bg-amber-500 px-4 py-2 text-sm font-bold text-black">✉ Invite Partner</Link><Link href="/admin/suppliers" className="rounded-xl border border-amber-500/50 px-4 py-2 text-sm font-semibold text-amber-300">Review Onboarding</Link></div></div></header>
  {error&&<div className="mt-6 rounded-xl border border-red-900 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}
  <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-7"><Metric label="Prospects" value={metrics.prospects}/><Metric label="Invites need action" value={metrics.inviteAction} alert={metrics.inviteAction>0}/><Metric label="Invite opened" value={metrics.opened}/><Metric label="Signup started" value={metrics.signup}/><Metric label="Onboarding" value={metrics.onboarding}/><Metric label="Awaiting review" value={metrics.review} alert={metrics.review>0}/><Metric label="Active" value={metrics.active}/></section>
  <section className="mt-7 grid gap-3 md:grid-cols-4"><Quick title="Discover" text="AI Supplier Scout finds real prospects for human review." href="/admin/ai-sales" cta="Find partners →"/><Quick title="Invite" text="AI drafts the introduction. You approve before sending." href="/admin/ai-sales/invitations" cta="Invite partner →"/><Quick title="Onboard & verify" text="See completion, submitted suppliers and review actions." href="/admin/suppliers" cta="Open enrollment →"/><Quick title="Manage" text="Track existing partner relationships and stages." href="#relationships" cta="View relationships ↓"/></section>
  <section className="mt-8 overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-950"><div className="flex items-center justify-between border-b border-zinc-800 p-5"><div><h2 className="font-semibold">Action Center</h2><p className="mt-1 text-xs text-zinc-500">Partners that need a human decision or follow-up.</p></div><button onClick={()=>void load()} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs">Refresh</button></div>{loading?<div className="p-12 text-center text-sm text-zinc-500">Loading partner operations…</div>:attention.length===0?<div className="p-12 text-center text-sm text-zinc-500">No partner enrollment actions need attention right now.</div>:<div className="divide-y divide-zinc-900">{attention.map(item=><div key={item.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-zinc-500">{item.detail}</p></div><div className="flex items-center gap-3"><span className="rounded-full border border-zinc-700 px-3 py-1 font-mono text-[10px] uppercase text-amber-300">{item.status.replaceAll("_"," ")}</span><Link href={item.href} className="text-sm font-semibold text-amber-400">{item.action} →</Link></div></div>)}</div>}</section>
  <section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Recruitment activity</h2><p className="text-xs text-zinc-500">Latest governed partner invitations</p></div><Link href="/admin/ai-sales/invitations" className="text-sm text-amber-400">Manage →</Link></div><div className="mt-4 space-y-2">{data.invitations.slice(0,6).map(i=><div key={i.id} className="rounded-xl border border-zinc-900 p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-medium">{i.business_name}</p><p className="text-xs text-zinc-500">{i.partner_type}</p></div><span className="text-[10px] uppercase text-amber-300">{i.status.replaceAll("_"," ")}</span></div></div>)}{!loading&&!data.invitations.length&&<p className="text-sm text-zinc-500">No invitations yet.</p>}</div></div><div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Enrollment & verification</h2><p className="text-xs text-zinc-500">Real supplier onboarding records</p></div><Link href="/admin/suppliers" className="text-sm text-amber-400">Review →</Link></div><div className="mt-4 space-y-2">{data.suppliers.slice(0,6).map(s=><Link href={`/admin/ai-sales/partners/${s.id}`} key={s.id} className="block rounded-xl border border-zinc-900 p-3 transition hover:border-amber-500/40"><div className="flex justify-between gap-3"><div><p className="text-sm font-medium">{s.businesses?.name||s.contact_name}</p><p className="text-xs text-zinc-500">{s.completion_percent||0}% complete · Open Partner 360 →</p></div><span className="text-[10px] uppercase text-amber-300">{s.onboarding_status.replaceAll("_"," ")}</span></div></Link>)}{!loading&&!data.suppliers.length&&<p className="text-sm text-zinc-500">No supplier onboarding records yet.</p>}</div></div></section>
  <section id="relationships" className="mt-8 overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-950"><div className="border-b border-zinc-800 p-5"><h2 className="font-semibold">Relationship pipeline</h2><p className="mt-1 text-xs text-zinc-500">Existing CRM partner relationships.</p></div>{!loading&&!data.partners.length?<div className="p-10 text-center text-sm text-zinc-500">No relationship records yet. Use AI discovery or Invite Partner above.</div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-zinc-900/60 text-xs uppercase text-zinc-500"><tr><th className="p-4">Partner</th><th className="p-4">Contact</th><th className="p-4">Email / phone</th><th className="p-4">Stage</th><th className="p-4">Action</th></tr></thead><tbody>{data.partners.map(p=><tr key={p.id} className="border-t border-zinc-900"><td className="p-4 font-semibold">{p.venue_or_promoter_name}</td><td className="p-4 text-zinc-400">{p.contact_person||"—"}</td><td className="p-4 text-zinc-400">{p.email_or_phone||"—"}</td><td className="p-4 text-amber-300">{p.outreach_stage.replaceAll("_"," ")}</td><td className="p-4"><Link href="/admin/ai-sales/invitations" className="text-amber-400">Invite / follow up →</Link></td></tr>)}</tbody></table></div>}</section>
  <div className="mt-7 flex flex-wrap gap-4 text-sm text-zinc-400"><Link href="/admin">← Admin Operations</Link><Link href="/admin/ai-sales">AI Sales</Link><Link href="/admin/ai-sales/invitations">Invitations</Link><Link href="/admin/suppliers">Supplier Enrollment</Link></div>
 </div></main>
}
function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <div className={`rounded-2xl border p-4 ${alert?"border-amber-500/50 bg-amber-500/10":"border-zinc-800 bg-zinc-950"}`}><p className="text-[11px] text-zinc-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function Quick({title,text,href,cta}:{title:string;text:string;href:string;cta:string}){return <Link href={href} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5 transition hover:border-amber-500/50"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p><p className="mt-4 text-sm font-semibold text-amber-400">{cta}</p></Link>}
