import { notFound } from "next/navigation";
import { supabaseAdmin } from "@/lib/supabase-admin";
import BookingForm from "../BookingForm";

export const dynamic = "force-dynamic";

export default async function ServicePage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ tripId?: string }> }) {
  const { slug } = await params;
  const { tripId } = await searchParams;
  const { data: s } = await supabaseAdmin.from("service_profiles").select("id,timezone,booking_notice_minutes,cancellation_policy,businesses!inner(name,slug,description,address,phone,whatsapp,website_url,logo_url,cover_image_url),service_categories(name),service_offerings(id,name,description,duration_minutes,price,currency,status,requires_confirmation)").eq("status","active").eq("booking_status","open").eq("businesses.slug",slug).eq("service_offerings.status","active").maybeSingle();
  if (!s) notFound();
  const offerings = ((s as any).service_offerings ?? []) as any[];
  const { data: staff } = await supabaseAdmin.from("service_staff").select("id,display_name,bio").eq("service_profile_id",(s as any).id).eq("status","active");
  const business = (s as any).businesses;
  return <main className="min-h-screen bg-[#f7f7f4] text-[#111]">
    <section className="bg-[#111] text-white"><div className="mx-auto max-w-6xl px-6 pb-14 pt-10 sm:px-10"><p className="text-[11px] font-semibold uppercase tracking-[.25em] text-white/45">{(s as any).service_categories?.name ?? "Services"}</p><div className="mt-7 flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{business.name}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/55">{business.description}</p></div><div className="shrink-0 rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-sm text-white/65">{business.address ?? "East Africa"}</div></div></div></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-6 py-12 lg:grid-cols-[1fr_420px] sm:px-10"><div><div className="mb-8 flex items-end justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-black/40">The menu</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Signature services</h2></div><span className="rounded-full bg-white px-4 py-2 text-xs text-black/45 shadow-sm">{offerings.length} services</span></div><div className="space-y-3">{offerings.map((x:any)=><details key={x.id} className="group rounded-2xl border border-black/8 bg-white p-5 shadow-[0_18px_55px_-45px_rgba(0,0,0,.5)]"><summary className="flex cursor-pointer list-none items-center justify-between gap-5"><div><h3 className="font-semibold">{x.name}</h3><p className="mt-1 text-sm text-black/45">{x.duration_minutes} min{x.requires_confirmation ? " · confirmation required" : " · instant confirmation"}</p></div><div className="flex items-center gap-4"><span className="text-sm font-semibold">{x.currency} {Number(x.price).toLocaleString()}</span><span className="text-black/35 transition group-open:rotate-45">＋</span></div></summary><p className="mt-4 max-w-xl text-sm leading-6 text-black/55">{x.description ?? "A professionally delivered service from this SafariPlug provider."}</p></details>)}</div><div className="mt-10 rounded-[1.75rem] bg-white p-6"><p className="text-[11px] font-semibold uppercase tracking-[.2em] text-black/40">Your specialists</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{(staff ?? []).map((person:any)=><div key={person.id} className="rounded-2xl border border-black/8 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-black text-xs font-semibold text-white">{person.display_name.split(" ").map((x:string)=>x[0]).slice(0,2).join("")}</div><p className="mt-3 font-semibold">{person.display_name}</p><p className="mt-1 text-sm text-black/45">{person.bio ?? "SafariPlug service specialist"}</p></div>)}</div></div></div><aside className="lg:sticky lg:top-6 lg:h-fit"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.22em] text-black/40">Live booking</p>{tripId && <div className="mb-3 rounded-xl border border-black/8 bg-white px-4 py-3 text-xs text-black/55">Booking from your SafariPlug journey</div>}{offerings.length ? <BookingForm profileId={(s as any).id} offerings={offerings} staff={staff ?? []} timezone={(s as any).timezone ?? "Africa/Nairobi"} tripId={tripId} /> : <div className="rounded-2xl bg-white p-6 text-sm text-black/50">No bookable services are currently listed.</div>}<p className="mt-4 text-center text-xs text-black/40">{(s as any).booking_notice_minutes ? `Bookings require ${Math.ceil((s as any).booking_notice_minutes / 60)}h notice.` : "Real availability is checked when you book."}</p></aside></section>
  </main>;
}
