import Link from "next/link";
import { notFound } from "next/navigation";
import { supabaseAdmin } from "@/lib/supabase-admin";
import BookingForm from "../BookingForm";

export const dynamic = "force-dynamic";

export default async function ServicePage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ tripId?: string }> }) {
  const { slug } = await params; const { tripId } = await searchParams;
  const { data:s } = await supabaseAdmin.from("service_profiles").select("id,timezone,booking_notice_minutes,cancellation_policy,businesses!inner(id,name,slug,description,address,phone,whatsapp,website_url,logo_url,cover_image_url,status),service_categories(name),service_offerings(id,name,description,duration_minutes,price,currency,status,requires_confirmation)").eq("status","active").eq("booking_status","open").eq("businesses.slug",slug).eq("businesses.status","active").eq("service_offerings.status","active").maybeSingle();
  if(!s) notFound();
  const profile=s as any; const offerings=(profile.service_offerings??[]) as any[]; const business=profile.businesses;
  const { data:staffRows }=await supabaseAdmin.from("service_staff").select("id,display_name,bio,personal_photo_url,verification_state,identity_liveness_verified_at,user_id").eq("service_profile_id",profile.id).eq("status","active").eq("verification_state","verified").not("user_id","is",null).not("personal_photo_url","is",null);
  const staffIds=(staffRows??[]).map((row:any)=>String(row.id));
  const { data:staffCases }=staffIds.length?await supabaseAdmin.from("verification_cases").select("subject_id,provider,status,expires_at").eq("subject_type","service_staff").in("subject_id",staffIds).eq("status","approved"): {data:[]};
  const approvedByStaff=new Map((staffCases??[]).filter((row:any)=>!row.expires_at||new Date(row.expires_at).getTime()>Date.now()).map((row:any)=>[String(row.subject_id),String(row.provider||"")]));
  const staff=(staffRows??[]).filter((row:any)=>approvedByStaff.get(String(row.id))==="human_review"||Boolean(row.identity_liveness_verified_at));
  const cover=business.cover_image_url||business.logo_url;
  return <main className="min-h-screen bg-[#f7f7f4] text-[#111]">
    <section className="bg-[#111] text-white"><div className="mx-auto max-w-6xl px-6 pb-14 pt-8 sm:px-10"><div className="flex items-center justify-between"><Link href="/services" className="text-xs font-semibold text-white/50 hover:text-white">← All services</Link><span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-[#e7c98d]">Booking open</span></div>{cover&&<div className="relative mt-8 aspect-[21/8] overflow-hidden rounded-[2rem] bg-white/5"><img src={cover} alt="" className="h-full w-full object-cover"/></div>}<div className="mt-8 flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.25em] text-[#c9a86a]">{profile.service_categories?.name??"Services"}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{business.name}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/55">{business.description}</p></div><div className="shrink-0 rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-sm text-white/65"><p>{business.address??"Location available from provider"}</p>{business.website_url&&<a href={business.website_url} target="_blank" rel="noreferrer" className="mt-2 block text-xs text-[#e7c98d]">Provider website ↗</a>}</div></div></div></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-6 py-12 lg:grid-cols-[1fr_420px] sm:px-10"><div><div className="mb-8 flex items-end justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-black/40">Choose what you need</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Services & prices</h2></div><span className="rounded-full bg-white px-4 py-2 text-xs text-black/45 shadow-sm">{offerings.length} services</span></div><div className="space-y-3">{offerings.map((x:any)=><details key={x.id} className="group rounded-2xl border border-black/8 bg-white p-5 shadow-[0_18px_55px_-45px_rgba(0,0,0,.5)]"><summary className="flex cursor-pointer list-none items-center justify-between gap-5"><div><h3 className="font-semibold">{x.name}</h3><p className="mt-1 text-sm text-black/45">{x.duration_minutes} min · {x.requires_confirmation?"provider confirmation":"confirmation on booking"}</p></div><div className="flex items-center gap-4"><span className="text-sm font-semibold">{x.currency} {Number(x.price).toLocaleString()}</span><span className="text-black/35 transition group-open:rotate-45">＋</span></div></summary><p className="mt-4 max-w-xl text-sm leading-6 text-black/55">{x.description??"Professionally delivered service from this SafariPlug provider."}</p></details>)}</div>
    <div className="mt-10 rounded-[1.75rem] bg-white p-6"><div className="flex items-end justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.2em] text-black/40">People</p><h2 className="mt-2 text-2xl font-semibold">Choose your specialist</h2></div><span className="text-xs text-black/40">{(staff??[]).length} available</span></div>{(staff??[]).length?<div className="mt-5 grid gap-3 sm:grid-cols-2">{(staff??[]).map((person:any)=><div key={person.id} className="rounded-2xl border border-black/8 p-4"><div className="h-16 w-16 overflow-hidden rounded-full bg-black">{person.personal_photo_url?<img src={person.personal_photo_url} alt={person.display_name} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center text-xs font-semibold text-white">{person.display_name.split(" ").map((x:string)=>x[0]).slice(0,2).join("")}</div>}</div><p className="mt-3 font-semibold">{person.display_name}</p><p className="mt-1 text-sm leading-5 text-black/45">{person.bio??"SafariPlug service specialist"}</p><span className="mt-2 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700">SafariPlug verified</span></div>)}</div>:<p className="mt-4 text-sm text-black/50">Choose “Any available specialist” when booking and SafariPlug will show the real open slots.</p>}</div>
    {profile.cancellation_policy&&<div className="mt-6 rounded-[1.5rem] border border-black/8 p-5"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-black/40">Cancellation policy</p><p className="mt-2 text-sm leading-6 text-black/55">{profile.cancellation_policy}</p></div>}</div>
    <aside className="lg:sticky lg:top-6 lg:h-fit"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.22em] text-black/40">Live booking</p>{tripId&&<div className="mb-3 rounded-xl border border-black/8 bg-white px-4 py-3 text-xs text-black/55">This booking will be added to your SafariPlug journey.</div>}{offerings.length?<BookingForm profileId={profile.id} offerings={offerings} staff={staff??[]} timezone={profile.timezone??"Africa/Nairobi"} tripId={tripId}/>:<div className="rounded-2xl bg-white p-6 text-sm text-black/50">No bookable services are currently listed.</div>}<p className="mt-4 text-center text-xs text-black/40">{profile.booking_notice_minutes?`Bookings require ${Math.ceil(profile.booking_notice_minutes/60)}h notice.`:"Real availability is checked when you book."}</p></aside></section>
  </main>;
}
