import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth/require-admin";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const dynamic = "force-dynamic";

type Business = { id:string; name:string; description:string|null; phone:string|null; email:string|null; whatsapp:string|null; website:string|null; instagram:string|null; status:string|null; city_id:string|null };
type Profile = { id:string; status:string|null; booking_status:string|null; service_categories:{name:string;slug:string}|{name:string;slug:string}[]|null; service_offerings:{id:string;name:string;price:number|null;currency:string|null;status:string|null;duration_minutes:number|null}[]|null; service_staff:{id:string;display_name:string|null;personal_photo_url:string|null;status:string|null}[]|null };

export default async function Partner360Page({params}:{params:Promise<{supplierId:string}>}){
 await requireAdmin(); const {supplierId}=await params;
 const {data:supplier}=await supabaseAdmin.from("supplier_accounts").select("id,user_id,business_id,prospect_id,partner_id,contact_name,invitation_status,onboarding_status,completion_percent,submitted_at,approved_at,created_at,businesses!inner(id,name,description,phone,email,whatsapp,website,instagram,status,city_id),service_profiles(id,status,booking_status,service_categories(name,slug),service_offerings(id,name,price,currency,status,duration_minutes),service_staff(id,display_name,personal_photo_url,status))").eq("id",supplierId).maybeSingle();
 if(!supplier) notFound();
 const business=(Array.isArray(supplier.businesses)?supplier.businesses[0]:supplier.businesses) as Business;
 const profiles=(supplier.service_profiles||[]) as Profile[];
 const [{data:verification},{data:invites},{data:relationship},{data:prospect}]=await Promise.all([
  supabaseAdmin.from("verification_cases").select("id,status,subject_type,created_at,updated_at").eq("subject_type","provider").eq("subject_id",business.id).order("created_at",{ascending:false}).limit(5),
  supabaseAdmin.from("partner_invitations").select("id,status,partner_type,contact_email,whatsapp_phone,created_at,sent_at,opened_at,signup_started_at").eq("onboarded_user_id",supplier.user_id).order("created_at",{ascending:false}).limit(10),
  supplier.partner_id?supabaseAdmin.from("safari_partners").select("id,venue_or_promoter_name,contact_person,email_or_phone,outreach_stage,notes,created_at").eq("id",supplier.partner_id).maybeSingle():Promise.resolve({data:null}),
  supplier.prospect_id?supabaseAdmin.from("ai_sales_prospects").select("id,business_name,category,city,status,opportunity_score,created_at").eq("id",supplier.prospect_id).maybeSingle():Promise.resolve({data:null}),
 ]);
 const offerings=profiles.flatMap(p=>p.service_offerings||[]); const staff=profiles.flatMap(p=>p.service_staff||[]); const personalPhotos=staff.filter(s=>Boolean(s.personal_photo_url)).length; const latestVerification=verification?.[0];
 const nextAction=nextActionFor(supplier.onboarding_status,Number(supplier.completion_percent||0),latestVerification?.status);
 return <main className="min-h-screen bg-[#070707] p-5 text-white md:p-10"><div className="mx-auto max-w-6xl"><Link href="/admin/ai-sales/partners" className="text-sm text-zinc-400 hover:text-white">← Partner CRM</Link>
 <header className="mt-5 flex flex-col justify-between gap-5 border-b border-zinc-800 pb-7 md:flex-row md:items-end"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.2em] text-amber-400">Partner 360</p><h1 className="mt-2 text-3xl font-bold">{business.name}</h1><p className="mt-2 text-sm text-zinc-400">{supplier.contact_name||"No contact name"} · {business.email||business.phone||"No contact channel"}</p></div><div className="flex flex-wrap gap-2"><Status label="Onboarding" value={supplier.onboarding_status}/><Status label="Business" value={business.status||"unknown"}/><Status label="Verification" value={latestVerification?.status||"not started"}/></div></header>
 <section className="mt-7 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-amber-300">Next action</p><h2 className="mt-2 text-xl font-semibold">{nextAction.title}</h2><p className="mt-1 text-sm text-zinc-300">{nextAction.detail}</p><div className="mt-4 flex flex-wrap gap-2">{nextAction.href&&<Link href={nextAction.href} className="rounded-xl bg-amber-500 px-4 py-2 text-sm font-bold text-black">{nextAction.cta}</Link>}<Link href="/admin/ai-sales/invitations" className="rounded-xl border border-zinc-700 px-4 py-2 text-sm">Invitation center</Link>{supplier.prospect_id&&<Link href={`/admin/ai-sales/edit/${supplier.prospect_id}`} className="rounded-xl border border-zinc-700 px-4 py-2 text-sm">Open prospect 360</Link>}</div></section>
 <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Onboarding" value={`${supplier.completion_percent||0}%`}/><Metric label="Offerings" value={String(offerings.length)}/><Metric label="Team" value={String(staff.length)}/><Metric label="Personal photos" value={`${personalPhotos}/${staff.length}`}/><Metric label="Invitations" value={String(invites?.length||0)}/></section>
 <div className="mt-7 grid gap-6 lg:grid-cols-2"><Card title="Business & contact"><Field label="Business" value={business.name}/><Field label="Contact" value={supplier.contact_name}/><Field label="Email" value={business.email}/><Field label="Phone" value={business.phone}/><Field label="WhatsApp" value={business.whatsapp}/><Field label="Website" value={business.website}/><Field label="Instagram" value={business.instagram}/></Card>
 <Card title="Enrollment & governance"><Field label="Invitation" value={supplier.invitation_status}/><Field label="Onboarding" value={supplier.onboarding_status}/><Field label="Completion" value={`${supplier.completion_percent||0}%`}/><Field label="Submitted" value={date(supplier.submitted_at)}/><Field label="Approved" value={date(supplier.approved_at)}/><Field label="Verification" value={latestVerification?.status||"Not started"}/><p className="mt-4 text-xs leading-5 text-zinc-500">Verification and activation remain governed. Partner 360 does not automatically verify, approve, publish, or open bookings.</p></Card></div>
 <section className="mt-7 rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">CRM relationship context</h2><p className="mt-1 text-xs text-zinc-500">Stable identifiers only. SafariPlug does not guess links from matching business names.</p></div><span className={`rounded-full border px-3 py-1 text-[10px] uppercase ${supplier.prospect_id||supplier.partner_id?"border-emerald-700 text-emerald-400":"border-zinc-700 text-zinc-500"}`}>{supplier.prospect_id||supplier.partner_id?"linked":"unlinked"}</span></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-zinc-900 p-4"><p className="text-xs uppercase text-zinc-500">Discovery prospect</p>{prospect?<><p className="mt-2 font-semibold">{prospect.business_name}</p><p className="mt-1 text-sm text-zinc-400">{prospect.category||"Uncategorized"} · {prospect.city||"City not recorded"}</p><p className="mt-2 text-xs text-zinc-500">Status {prospect.status||"unknown"} · Opportunity {prospect.opportunity_score??"—"}</p><Link href={`/admin/ai-sales/edit/${prospect.id}`} className="mt-3 inline-block text-sm font-semibold text-amber-400">Open prospect 360 →</Link></>:<p className="mt-2 text-sm text-zinc-500">No stable prospect link recorded.</p>}</div><div className="rounded-xl border border-zinc-900 p-4"><p className="text-xs uppercase text-zinc-500">Partner relationship</p>{relationship?<><p className="mt-2 font-semibold">{relationship.venue_or_promoter_name}</p><p className="mt-1 text-sm text-zinc-400">{relationship.contact_person||relationship.email_or_phone||"No relationship contact recorded"}</p><p className="mt-2 text-xs text-zinc-500">Stage {(relationship.outreach_stage||"unknown").replaceAll("_"," ")}</p></>:<p className="mt-2 text-sm text-zinc-500">No stable partner relationship link recorded.</p>}</div></div></section>
 <section className="mt-7 rounded-2xl border border-zinc-800 bg-zinc-950"><div className="border-b border-zinc-800 p-5"><h2 className="font-semibold">Inventory & team readiness</h2></div><div className="grid gap-5 p-5 md:grid-cols-2"><div><p className="text-xs uppercase text-zinc-500">Offerings</p>{offerings.length?offerings.map(o=><div key={o.id} className="mt-3 rounded-xl border border-zinc-800 p-3"><p className="font-medium">{o.name}</p><p className="mt-1 text-xs text-zinc-500">{o.price!=null?`${o.currency||""} ${o.price}`:"No recorded price"} · {o.status||"unknown"}</p></div>):<p className="mt-3 text-sm text-zinc-500">No service offerings recorded.</p>}</div><div><p className="text-xs uppercase text-zinc-500">Team identity</p>{staff.length?staff.map(s=><div key={s.id} className="mt-3 flex items-center justify-between rounded-xl border border-zinc-800 p-3"><div><p className="font-medium">{s.display_name||"Unnamed team member"}</p><p className="text-xs text-zinc-500">{s.status||"unknown"}</p></div><span className={`text-xs ${s.personal_photo_url?"text-emerald-400":"text-amber-300"}`}>{s.personal_photo_url?"Photo recorded":"Photo missing"}</span></div>):<p className="mt-3 text-sm text-zinc-500">No staff records.</p>}</div></div></section>
 <section className="mt-7 rounded-2xl border border-zinc-800 bg-zinc-950"><div className="border-b border-zinc-800 p-5"><h2 className="font-semibold">Recruitment timeline</h2><p className="mt-1 text-xs text-zinc-500">Invitation-link activity, not email pixel tracking.</p></div><div className="divide-y divide-zinc-900">{invites?.length?invites.map(i=><div key={i.id} className="p-4"><div className="flex justify-between gap-4"><p className="font-medium">{i.partner_type}</p><span className="font-mono text-xs uppercase text-amber-300">{i.status.replaceAll("_"," ")}</span></div><p className="mt-1 text-xs text-zinc-500">Sent {date(i.sent_at)} · Link opened {date(i.opened_at)} · Signup started {date(i.signup_started_at)}</p></div>):<p className="p-5 text-sm text-zinc-500">No linked recruitment invitation found for this supplier account.</p>}</div></section>
 </div></main>
}
function nextActionFor(status:string,completion:number,verification?:string){if(status==="submitted")return{title:"Review supplier submission",detail:"This partner has submitted onboarding and is waiting for an admin decision.",href:"/admin/suppliers",cta:"Open supplier review"};if(status==="changes_requested")return{title:"Waiting for partner changes",detail:"Changes were requested. Do not activate until the partner resubmits and requirements are reviewed.",href:"/admin/suppliers",cta:"Review status"};if(status==="approved"||status==="live")return{title:verification==="approved"?"Partner is operationally approved":"Check verification before full activation",detail:verification==="approved"?"Continue relationship management and inventory quality checks.":"Supplier approval exists, but provider verification should be reviewed independently.",href:"/admin/suppliers",cta:"Open governance"};if(completion<100)return{title:"Onboarding is incomplete",detail:`The recorded onboarding completion is ${completion}%. Follow up on missing profile, inventory, identity or operational requirements.`,href:"/admin/ai-sales/invitations",cta:"Open follow-up center"};return{title:"Prepare for supplier review",detail:"Onboarding appears complete but is not yet in an approved/live state.",href:"/admin/suppliers",cta:"Open supplier review"}}
function Status({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-2"><p className="text-[10px] uppercase text-zinc-500">{label}</p><p className="mt-1 text-xs font-semibold capitalize text-amber-300">{value.replaceAll("_"," ")}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>}
function Field({label,value}:{label:string;value:string|null|undefined}){return <div className="flex justify-between gap-4 border-t border-zinc-900 py-2 text-sm"><span className="text-zinc-500">{label}</span><span className="max-w-[65%] text-right">{value||"—"}</span></div>}
function date(value:string|null|undefined){return value?new Date(value).toLocaleString():"—"}
