import Link from "next/link";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase-server";

export default async function LocalAvailabilityPage(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/account/login?next=/locals/onboarding/availability");const {data:profile}=await db.from("local_profiles").select("id,timezone").eq("user_id",user.id).maybeSingle();if(!profile)redirect("/locals/onboarding");const {data:slots}=await db.from("local_availability").select("id,available_on,start_time,end_time,timezone,status").eq("local_id",profile.id).gte("available_on",new Date().toISOString().slice(0,10)).order("available_on").order("start_time");
async function add(formData:FormData){"use server";const auth=await createClient();const {data:{user:current}}=await auth.auth.getUser();if(!current)redirect("/account/login");const {data:p}=await auth.from("local_profiles").select("id,timezone").eq("user_id",current.id).maybeSingle();if(!p)redirect("/locals/onboarding");const date=String(formData.get("available_on")||"");const start=String(formData.get("start_time")||"")||null;const end=String(formData.get("end_time")||"")||null;if(!date||date<new Date().toISOString().slice(0,10)||start&&end&&end<=start)redirect("/locals/onboarding/availability?error=invalid");await auth.from("local_availability").insert({local_id:p.id,available_on:date,start_time:start,end_time:end,timezone:p.timezone||"Africa/Nairobi",status:"available"});revalidatePath("/locals/onboarding/availability");}
async function remove(formData:FormData){"use server";const auth=await createClient();const id=String(formData.get("id")||"");if(id)await auth.from("local_availability").delete().eq("id",id);revalidatePath("/locals/onboarding/availability");}
return <main className="min-h-screen bg-[#f7f7f4] px-6 py-12"><div className="mx-auto max-w-3xl"><Link href="/locals/onboarding" className="text-sm font-semibold">← Local profile</Link><p className="mt-8 text-[11px] font-bold uppercase tracking-[.2em] text-black/40">Availability</p><h1 className="mt-3 text-4xl font-semibold">When can travelers request you?</h1><p className="mt-3 text-sm leading-6 text-black/55">Publishing availability lets travelers see potential times. It is not a booking guarantee; each specific-Local request still requires acceptance.</p><form action={add} className="mt-7 grid gap-4 rounded-[2rem] bg-white p-6 sm:grid-cols-4"><label className="grid gap-2 text-sm font-semibold">Date<input name="available_on" type="date" required min={new Date().toISOString().slice(0,10)} className="rounded-xl border p-3 font-normal"/></label><label className="grid gap-2 text-sm font-semibold">Start<input name="start_time" type="time" className="rounded-xl border p-3 font-normal"/></label><label className="grid gap-2 text-sm font-semibold">End<input name="end_time" type="time" className="rounded-xl border p-3 font-normal"/></label><button className="self-end rounded-full bg-black px-5 py-3 text-sm font-bold text-white">Add time</button></form><div className="mt-6 grid gap-3">{slots?.length?slots.map(s=><div key={s.id} className="flex items-center justify-between gap-4 rounded-2xl bg-white p-4"><div><p className="font-semibold">{s.available_on}</p><p className="text-sm text-black/50">{s.start_time?String(s.start_time).slice(0,5):"Any time"}{s.end_time?`–${String(s.end_time).slice(0,5)}`:""} · {s.timezone}</p></div><form action={remove}><input type="hidden" name="id" value={s.id}/><button className="text-sm font-semibold text-red-700">Remove</button></form></div>):<div className="rounded-2xl bg-white p-5 text-sm text-black/50">No future availability published yet.</div>}</div><Link href="/locals/onboarding/verification" className="mt-6 inline-block text-sm font-semibold">Identity verification →</Link></div></main>}
