"use client";

import { useState } from "react";

export default function SuppliersAdminPage() {
  const [form, setForm] = useState({ businessName: "", contactName: "", email: "", phone: "", categorySlug: "barbers", cityId: "", notes: "" });
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const set = (key: string, value: string) => setForm((f) => ({ ...f, [key]: value }));
  async function invite() { setSaving(true); setMessage(""); const r = await fetch("/api/admin/suppliers/invite", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); setMessage(r.ok ? "Supplier created and invitation email sent." : d.error || "Unable to create supplier."); setSaving(false); if (r.ok) setForm({ businessName: "", contactName: "", email: "", phone: "", categorySlug: "barbers", cityId: "", notes: "" }); }
  return <main className="mx-auto max-w-4xl px-6 py-10"><p className="text-sm uppercase tracking-[.2em] text-black/40">Admin · Partner CRM</p><h1 className="mt-2 text-4xl font-semibold">Create supplier account</h1><p className="mt-3 max-w-2xl text-black/60">Create the supplier shell, send a secure invitation, and let the supplier create their own password and finish their profile.</p><section className="mt-8 grid gap-5 rounded-2xl border border-black/10 p-6 md:grid-cols-2">
    {[["businessName","Business name"],["contactName","Contact person"],["email","Email"],["phone","Phone"],["cityId","City ID (optional)"]].map(([key,label]) => <label key={key} className="text-sm"><span className="mb-1 block font-medium">{label}</span><input value={(form as any)[key]} onChange={(e) => set(key,e.target.value)} className="w-full rounded-xl border border-black/15 px-3 py-2.5" /></label>)}
    <label className="text-sm"><span className="mb-1 block font-medium">Supplier category</span><select value={form.categorySlug} onChange={(e) => set("categorySlug",e.target.value)} className="w-full rounded-xl border border-black/15 px-3 py-2.5">{[["barbers","Barbers"],["hair-beauty","Hair & Beauty"],["spas-massage","Spas & Massage"],["tattoo-body-art","Tattoo Artists & Body Art"],["nails","Nails"],["lashes-brows","Lashes & Brows"],["fitness","Fitness"],["tours-local-guides","Tours & Local Guides"],["private-chefs-cooking","Private Chefs & Cooking"],["wellness","Wellness"]].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>
    <label className="text-sm md:col-span-2"><span className="mb-1 block font-medium">Internal notes</span><textarea value={form.notes} onChange={(e) => set("notes",e.target.value)} rows={4} className="w-full rounded-xl border border-black/15 px-3 py-2.5" /></label>
    <div className="md:col-span-2"><button onClick={invite} disabled={saving} className="rounded-full bg-black px-5 py-2.5 text-sm text-white disabled:opacity-50">{saving ? "Creating…" : "Create & invite supplier"}</button>{message && <p className="mt-3 text-sm">{message}</p>}</div>
  </section><section className="mt-8 rounded-2xl bg-black/[.04] p-6"><h2 className="font-semibold">Supplier flow</h2><ol className="mt-3 space-y-2 text-sm text-black/65"><li>1. SafariPlug creates the supplier account and business profile.</li><li>2. Supplier receives an invitation email and creates their password.</li><li>3. Supplier completes business details, services, pricing, availability and images.</li><li>4. Supplier submits for review; SafariPlug approves before the profile goes live.</li></ol></section></main>;
}
