import Link from "next/link";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth/require-admin";
import { supabaseAdmin } from "@/lib/supabase-admin";
export const dynamic="force-dynamic";
type Payout={id:string;appointment_id:string|null;service_profile_id:string|null;provider_user_id:string;currency:string;gross_amount:number;platform_fee_percent:number;platform_fee_amount:number;processor_fee_amount:number;refund_amount:number;provider_net_amount:number;status:string;paid_at:string|null;created_at:string};
type PaymentIntent={id:string;trip_id:string;checkout_attempt_id:string;currency:string;amount:number;status:string;provider:string;provider_reference:string|null;created_at:string};
const money=(n:number,c:string)=>`${c} ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const activeLiability=new Set(["eligible","approved","processing","held"]);
export default async function AccountingPage(){try{await requireAdmin();}catch{redirect("/admin/login");}
 const [pr,ir]=await Promise.all([supabaseAdmin.from("service_provider_payouts").select("id,appointment_id,service_profile_id,provider_user_id,currency,gross_amount,platform_fee_percent,platform_fee_amount,processor_fee_amount,refund_amount,provider_net_amount,status,paid_at,created_at").order("created_at",{ascending:false}).limit(500),supabaseAdmin.from("trip_package_payment_intents").select("id,trip_id,checkout_attempt_id,currency,amount,status,provider,provider_reference,created_at").order("created_at",{ascending:false}).limit(250)]);
 const payouts=(pr.data||[]) as Payout[], payments=(ir.data||[]) as PaymentIntent[];const currencies=[...new Set(payouts.map(x=>x.currency))];const paymentCurrencies=[...new Set(payments.map(x=>x.currency))];const sourceErrors=[pr.error,ir.error].filter(Boolean);const sourceCaps=[] as string[];if(payouts.length>=500)sourceCaps.push("service payouts (500-row cap)");if(payments.length>=250)sourceCaps.push("package payment intents (250-row cap)");
 return <main className="min-h-screen bg-[#070707] px-5 py-10 text-white md:px-10"><div className="mx-auto max-w-7xl"><header className="border-b border-zinc-800 pb-7"><p className="font-mono text-[11px] font-bold uppercase tracking-[.22em] text-emerald-400">SafariPlug // Finance OS</p><h1 className="mt-2 text-4xl font-bold">Sales, Commissions & Accounting</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">Financial control from recorded SafariPlug marketplace transactions. Gross sales, commissions, fees, refunds, provider liabilities and payouts remain traceable to their source records. Payment intents are shown separately and never counted as booked revenue.</p></header>
 {sourceErrors.length?<div className="mt-6 rounded-2xl border border-red-900/40 bg-red-950/20 p-5 text-sm text-red-200">One or more Finance OS sources could not be loaded. Totals below must not be treated as complete.</div>:null}
 {sourceCaps.length?<div className="mt-4 rounded-2xl border border-amber-900/40 bg-amber-950/20 p-5 text-sm text-amber-200">Source row limits were reached: {sourceCaps.join(", ")}. This dashboard is showing a partial operational window; use governed reporting/export before relying on totals.</div>:null}
 <nav className="mt-6 flex flex-wrap gap-2"><Anchor href="#sales" label="Sales"/><Anchor href="#commissions" label="Commissions"/><Anchor href="#payables" label="Payables"/><Anchor href="/admin/payouts" label="Payouts"/><Anchor href="#refunds" label="Refunds"/><Anchor href="/admin/accounting/refunds" label="Refund review"/><Anchor href="/admin/accounting/reconciliation" label="Reconciliation"/><Anchor href="/admin/accounting/reports" label="Reports"/></nav>
 <section className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Card title="Loaded payout rows" value={String(payouts.length)} text="Payout-backed marketplace economics loaded in this dashboard"/><Card title="Payment intents" value={String(payments.length)} text="Kept outside booked sales until financially realized"/><Card title="Paid vendor payouts" value={String(payouts.filter(x=>x.status==="paid").length)} text="Completed disbursements"/><Card title="Outstanding payables" value={String(payouts.filter(x=>activeLiability.has(x.status)).length)} text="Eligible, approved, processing or held"/></section>
 <section id="sales" className="mt-8"><Heading title="Sales & marketplace economics" text="Currency-specific totals only; no fabricated FX conversion."/><div className="mt-4 grid gap-3 lg:grid-cols-2">{currencies.map(c=>{const r=payouts.filter(x=>x.currency===c),sum=(k:keyof Payout)=>r.reduce((a,x)=>a+Number(x[k]||0),0);return <div key={c} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex justify-between"><h3 className="text-lg font-semibold">{c}</h3><span className="text-xs text-zinc-500">{r.length} ledger rows</span></div><dl className="mt-5 grid grid-cols-2 gap-5 md:grid-cols-3"><Money label="Gross" value={money(sum("gross_amount"),c)}/><Money label="SafariPlug commission" value={money(sum("platform_fee_amount"),c)}/><Money label="Processor fees" value={money(sum("processor_fee_amount"),c)}/><Money label="Refunds" value={money(sum("refund_amount"),c)}/><Money label="Vendor net" value={money(sum("provider_net_amount"),c)}/><Money label="Paid vendor net" value={money(r.filter(x=>x.status==="paid").reduce((a,x)=>a+Number(x.provider_net_amount||0),0),c)}/></dl></div>})}{!currencies.length&&<Empty/>}</div></section>
 <section id="commissions" className="mt-8"><Heading title="Commission ledger" text="SafariPlug platform fees recorded against provider payout economics."/><div className="mt-4 overflow-x-auto rounded-2xl border border-zinc-800 bg-zinc-950"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs uppercase text-zinc-500"><tr><th className="p-4">Source</th><th>Gross</th><th>Commission</th><th>Rate</th><th>Vendor net</th><th>Status</th></tr></thead><tbody>{payouts.slice(0,50).map(x=><tr key={x.id} className="border-t border-zinc-900"><td className="p-4 font-mono text-xs">{x.appointment_id?.slice(0,8)||x.id.slice(0,8)}</td><td>{money(x.gross_amount,x.currency)}</td><td>{money(x.platform_fee_amount,x.currency)}</td><td>{Number(x.platform_fee_percent||0)}%</td><td>{money(x.provider_net_amount,x.currency)}</td><td className="capitalize text-zinc-400">{x.status}</td></tr>)}</tbody></table>{!payouts.length&&<Empty/>}</div></section>
 <div className="mt-8 grid gap-5 lg:grid-cols-2"><section id="payables"><Panel title="Vendor payables">{currencies.map(c=>{const rows=payouts.filter(x=>x.currency===c&&activeLiability.has(x.status));return <Line key={c} left={`${c} outstanding`} right={money(rows.reduce((a,x)=>a+Number(x.provider_net_amount||0),0),c)} sub={`${rows.length} payout records`}/>})}{!currencies.length&&<Empty/>}<Link href="/admin/payouts" className="mt-4 inline-block text-sm font-semibold text-emerald-400">Open governed payout operations →</Link></Panel></section>
 <section id="refunds"><Panel title="Refunds">{currencies.map(c=>{const rows=payouts.filter(x=>x.currency===c&&Number(x.refund_amount)>0);return <Line key={c} left={`${c} recorded refunds`} right={money(rows.reduce((a,x)=>a+Number(x.refund_amount||0),0),c)} sub={`${rows.length} affected records`}/>})}{!currencies.length&&<Empty/>}<Link href="/admin/accounting/refunds" className="mt-4 inline-block text-sm font-semibold text-emerald-400">Open refund review →</Link></Panel></section></div>
 <section id="reconciliation" className="mt-8"><Heading title="Reconciliation control" text="Payment orchestration remains separate from realized marketplace economics so an initiated payment cannot silently become revenue."/><div className="mt-4"><Link href="/admin/accounting/reconciliation" className="inline-flex rounded-xl border border-emerald-700/50 px-4 py-2 text-sm font-semibold text-emerald-300">Open reconciliation center →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{paymentCurrencies.map(c=>{const r=payments.filter(x=>x.currency===c);return <div key={c} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><h3 className="font-semibold">{c} package payment intents</h3><div className="mt-4 space-y-2">{[...new Set(r.map(x=>x.status))].map(status=><Line key={status} left={status.replaceAll("_"," ")} right={String(r.filter(x=>x.status===status).length)} sub={money(r.filter(x=>x.status===status).reduce((a,x)=>a+Number(x.amount||0),0),c)}/>)}</div></div>})}{!paymentCurrencies.length&&<Empty/>}</div></section>
 <section id="reports" className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><Heading title="Financial reporting foundation" text="Current reports are operational ledger views. Formal tax, statutory accounting, invoices and recognized-revenue rules require their own governed accounting policy before being represented as financial statements."/><div className="mt-4 flex flex-wrap gap-2"><Link href="/admin/accounting/reports" className="rounded-xl border border-emerald-700/50 px-4 py-2 text-sm text-emerald-300">Open finance reports</Link><Link href="/admin/payouts" className="rounded-xl border border-zinc-700 px-4 py-2 text-sm">Payout report</Link><Link href="/admin/crm" className="rounded-xl border border-zinc-700 px-4 py-2 text-sm">Partner CRM</Link></div></section>
 <footer className="mt-8 flex flex-wrap gap-4 border-t border-zinc-800 pt-5 text-sm text-zinc-400"><Link href="/admin/crm">← AI CRM</Link><Link href="/admin">Command Center</Link><Link href="/admin/payouts">Payouts</Link></footer></div></main>}
function Anchor({href,label}:{href:string;label:string}){return <Link href={href} className="rounded-full border border-zinc-800 bg-zinc-950 px-4 py-2 text-xs text-zinc-300 hover:border-emerald-500/50">{label}</Link>}
function Heading({title,text}:{title:string;text:string}){return <div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-zinc-500">{text}</p></div>}
function Card({title,value,text}:{title:string;value:string;text:string}){return <div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><p className="text-xs text-zinc-500">{title}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-zinc-600">{text}</p></div>}
function Money({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-zinc-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="h-full rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><h2 className="mb-3 text-lg font-semibold">{title}</h2>{children}</div>}
function Line({left,right,sub}:{left:string;right:string;sub:string}){return <div className="flex justify-between gap-4 border-t border-zinc-900 py-3 text-sm"><div><p className="capitalize">{left}</p><p className="text-xs text-zinc-500">{sub}</p></div><p className="font-medium">{right}</p></div>}
function Empty(){return <p className="py-5 text-sm text-zinc-500">No recorded financial data yet.</p>}
