"use server";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { revalidatePath } from "next/cache";
import { AdminAuthError,requireAdmin } from "@/lib/auth/require-admin";
export type SalesScoutFormState={status:"idle"|"success"|"error";message:string};
const SCOUT_CITIES=["Nairobi","Mombasa","Diani","Kilifi","Malindi","Watamu","Lamu","Zanzibar","Kampala","Dar es Salaam","Accra","Lagos","Cape Town","Johannesburg","Cairo","Casablanca"] as const;
const SCOUT_CATEGORIES=["Barbers","Hair & Beauty","Spas & Massage","Tattoo Artists & Body Art","Nails","Lashes & Brows","Fitness & Personal Training","Yoga/Pilates/Mindfulness","Diving & Marine","Surfing & Board Sports","Water Sports & Kite","Tours & Local Guides","Photography & Content","Private Chefs & Cooking","Hotels","Restaurants","Nightlife","Tour Operators","Experiences"] as const;
function clean(v:unknown){return typeof v==="string"?v.trim():""}
async function enqueue(city:string,category:string,options?:{dedupeHours?:number}){const dedupeHours=Math.max(0,Number(options?.dedupeHours||0));if(dedupeHours>0){const cutoff=new Date(Date.now()-dedupeHours*60*60*1000).toISOString();const {data:existing,error:existingError}=await supabaseAdmin.from("supplier_scout_jobs").select("id,status,created_at").eq("city",city).eq("category",category).in("status",["queued","running","completed"]).gte("created_at",cutoff).order("created_at",{ascending:false}).limit(1).maybeSingle();if(existingError)throw existingError;if(existing)return {id:existing.id as string,created:false,status:String(existing.status)}}const {data,error}=await supabaseAdmin.from("supplier_scout_jobs").insert({city,category,status:"queued",queued_at:new Date().toISOString()}).select("id,status").single();if(error)throw error;return {id:data.id as string,created:true,status:String(data.status)}}
export async function runSalesScout(formData:FormData){try{await requireAdmin()}catch(e:unknown){if(e instanceof AdminAuthError)throw new Error(e.message);throw new Error(e instanceof Error?e.message:"Request failed")}const city=clean(formData.get("city"))||"Nairobi",category=clean(formData.get("category"))||"Hotels";if(!SCOUT_CITIES.includes(city as typeof SCOUT_CITIES[number])||!SCOUT_CATEGORIES.includes(category as typeof SCOUT_CATEGORIES[number]))throw new Error("Invalid Supplier Scout city or category");const queued=await enqueue(city,category);revalidatePath("/admin/ai-sales");return {jobId:queued.id,city,category,created:queued.created}}
export async function runSalesScoutForm(_previous:SalesScoutFormState,formData:FormData):Promise<SalesScoutFormState>{try{const r=await runSalesScout(formData);return {status:"success",message:`${r.created?"Supplier Scout queued":"Supplier Scout already has a recent job"} for ${r.category} in ${r.city}. You can leave this page; discovery will continue in the background. Job ${r.jobId.slice(0,8)}.`}}catch(e:unknown){console.error("SUPPLIER SCOUT QUEUE ERROR",e);return {status:"error",message:`Supplier Scout failed to queue: ${e instanceof Error?e.message:"Request failed"}`}}}
export async function runScheduledSalesScout(){const pairs=SCOUT_CITIES.flatMap(city=>SCOUT_CATEGORIES.map(category=>({city,category})));const dayIndex=Math.floor(Date.now()/86_400_000),start=(dayIndex*6)%pairs.length,selected=Array.from({length:6},(_,i)=>pairs[(start+i)%pairs.length]);const jobs:string[]=[];let queued=0,skipped=0;for(const pair of selected){const result=await enqueue(pair.city,pair.category,{dedupeHours:24});jobs.push(result.id);if(result.created)queued+=1;else skipped+=1}return {queued,skipped,jobs,selected}}
