"use server";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { revalidatePath } from "next/cache";
import { AdminAuthError,requireAdmin } from "@/lib/auth/require-admin";
export type SalesScoutFormState={status:"idle"|"success"|"error";message:string};
const SCOUT_CITIES=["Nairobi","Mombasa","Diani","Kilifi","Malindi","Watamu","Lamu","Zanzibar","Kampala","Dar es Salaam","Accra","Lagos","Cape Town","Johannesburg","Cairo","Casablanca"] as const;
const SCOUT_CATEGORIES=["Barbers","Hair & Beauty","Spas & Massage","Tattoo Artists & Body Art","Nails","Lashes & Brows","Fitness & Personal Training","Yoga/Pilates/Mindfulness","Diving & Marine","Surfing & Board Sports","Water Sports & Kite","Tours & Local Guides","Photography & Content","Private Chefs & Cooking","Hotels","Restaurants","Nightlife","Tour Operators","Experiences"] as const;
function clean(v:unknown){return typeof v==="string"?v.trim():""}
async function enqueue(city:string,category:string){const {data,error}=await supabaseAdmin.from("supplier_scout_jobs").insert({city,category,status:"queued",queued_at:new Date().toISOString()}).select("id").single();if(error)throw error;return data.id as string}
export async function runSalesScout(formData:FormData){try{await requireAdmin()}catch(e:unknown){if(e instanceof AdminAuthError)throw new Error(e.message);throw new Error(e instanceof Error?e.message:"Request failed")}const city=clean(formData.get("city"))||"Nairobi",category=clean(formData.get("category"))||"Hotels";if(!SCOUT_CITIES.includes(city as typeof SCOUT_CITIES[number])||!SCOUT_CATEGORIES.includes(category as typeof SCOUT_CATEGORIES[number]))throw new Error("Invalid Supplier Scout city or category");const jobId=await enqueue(city,category);revalidatePath("/admin/ai-sales");return {jobId,city,category}}
export async function runSalesScoutForm(_previous:SalesScoutFormState,formData:FormData):Promise<SalesScoutFormState>{try{const r=await runSalesScout(formData);return {status:"success",message:`Supplier Scout queued for ${r.category} in ${r.city}. You can leave this page; discovery will continue in the background. Job ${r.jobId.slice(0,8)}.`}}catch(e:unknown){console.error("SUPPLIER SCOUT QUEUE ERROR",e);return {status:"error",message:`Supplier Scout failed to queue: ${e instanceof Error?e.message:"Request failed"}`}}}
export async function runScheduledSalesScout(){const pairs=SCOUT_CITIES.flatMap(city=>SCOUT_CATEGORIES.map(category=>({city,category})));const dayIndex=Math.floor(Date.now()/86_400_000),start=(dayIndex*6)%pairs.length,selected=Array.from({length:6},(_,i)=>pairs[(start+i)%pairs.length]);const jobs:string[]=[];for(const pair of selected)jobs.push(await enqueue(pair.city,pair.category));return {queued:jobs.length,jobs,selected}}
