import OpenAI from "openai";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { scoreProspect } from "./scoring";

const CITY_COUNTRY: Record<string,string>={Nairobi:"Kenya",Mombasa:"Kenya",Diani:"Kenya",Kilifi:"Kenya",Malindi:"Kenya",Watamu:"Kenya",Lamu:"Kenya",Zanzibar:"Tanzania",Kampala:"Uganda","Dar es Salaam":"Tanzania",Accra:"Ghana",Lagos:"Nigeria","Cape Town":"South Africa",Johannesburg:"South Africa",Cairo:"Egypt",Casablanca:"Morocco"};
type Job={id:string;city:string;category:string;attempt_count:number;max_attempts:number};
type Prospect={business_name:string;category:string;city:string;website?:string;instagram?:string;facebook?:string;contact_email?:string;phone?:string;source_url:string;source_name:string;description:string;notes?:string};
function text(v:unknown){return typeof v==="string"?v.trim():""}
function url(v:unknown){const s=text(v);if(!s)return undefined;try{const u=new URL(s);if(!["http:","https:"].includes(u.protocol)||u.hostname.includes("example.com"))return undefined;return s}catch{return undefined}}
function email(v:unknown){const s=text(v),l=s.toLowerCase();if(!s||l.includes("[email")||l.includes("protected")||l.includes("example.")||l.includes("noreply")||l.includes("no-reply")||/[\[\]<>\s]/.test(s))return undefined;return /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(s)?s:undefined}
function phone(v:unknown){const s=text(v);return s.replace(/\D/g,"").length>=7?s:undefined}
function prompt(city:string,category:string){return [`Find real businesses in ${city}, ${CITY_COUNTRY[city]||"Africa"} operating in ${category} that could be SafariPlug partners.`,`Use live web search and perform contact enrichment for every candidate. Search official website/contact pages and official social profiles for a public business email or phone.`,`Prioritize verified public business email or phone. If neither exists, include a business only with a verified official website, Instagram URL, or Facebook URL for later human research.`,`Do not return a business with no email, phone, official website, official Instagram, and official Facebook. Never invent contact data. Never return obfuscated/redacted emails such as [email protected], email protected, example addresses, or no-reply addresses.`,`Only use public business information. Return at most 10. Return JSON only: {"prospects":[{"business_name":"string","category":"${category}","city":"${city}","website":"string or null","instagram":"string or null","facebook":"string or null","contact_email":"string or null","phone":"string or null","description":"string","source_url":"string","source_name":"string","notes":"string or null"}]}`].join("\n")}
function parse(raw:string,city:string,category:string):Prospect[]{let data:unknown;try{data=JSON.parse(raw)}catch{return []}const rows=(data as {prospects?:unknown[]})?.prospects;if(!Array.isArray(rows))return [];return rows.slice(0,10).flatMap((r)=>{if(!r||typeof r!=="object")return [];const x=r as Record<string,unknown>;const business_name=text(x.business_name),description=text(x.description),source_url=url(x.source_url),source_name=text(x.source_name);if(!business_name||text(x.city).toLowerCase()!==city.toLowerCase()||text(x.category)!==category||!description||!source_url||!source_name)return [];const website=url(x.website),instagram=url(x.instagram),facebook=url(x.facebook),contact_email=email(x.contact_email),p=phone(x.phone);if(!contact_email&&!p&&!website&&!instagram&&!facebook)return [];const readiness=contact_email||p?"Contact-ready: public email or phone found.":"Needs contact research: official public web/social property found, but no public email or phone was verified.";return [{business_name,category,city,website,instagram,facebook,contact_email,phone:p,description,source_url,source_name,notes:[text(x.notes),readiness,`Source: ${source_name} - ${source_url}`].filter(Boolean).join("\n")}]} )}
function client(){if(!process.env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is not configured");return new OpenAI({apiKey:process.env.OPENAI_API_KEY})}
export async function startSupplierScout(job:Job){return client().responses.create({model:process.env.OPENAI_SALES_SCOUT_MODEL||"gpt-5-mini",tools:[{type:"web_search"}],background:true,input:[{role:"system",content:"You are SafariPlug Supplier Discovery for Africa. Find real businesses and verified public contact paths. Never fabricate. Return JSON only."},{role:"user",content:prompt(job.city,job.category)}]})}
export async function pollSupplierScout(id:string){const r=await client().responses.retrieve(id);return {status:r.status||"unknown",outputText:r.output_text?.trim()||"",error:(r as unknown as {error?:{message?:string}}).error?.message||null}}
export async function finalizeSupplierScout(job:Job,raw:string){const prospects=parse(raw,job.city,job.category);let inserted=0,contactReady=0,needsResearch=0;for(const p of prospects){if(p.contact_email||p.phone)contactReady++;else needsResearch++;const {data:existing,error:lookupError}=await supabaseAdmin.from("ai_sales_prospects").select("id").eq("business_name",p.business_name).eq("city",job.city).maybeSingle();if(lookupError)throw lookupError;if(existing)continue;const intelligence=scoreProspect({business_name:p.business_name,category:p.category,city:p.city});const {error}=await supabaseAdmin.from("ai_sales_prospects").insert({...p,opportunity_score:intelligence.score,notes:[`${intelligence.priority} priority. ${intelligence.reason}`,p.notes].filter(Boolean).join("\n"),status:"pending_review",review_status:"pending_review"});if(error)throw error;inserted++}return {qualified:prospects.length,contactReady,needsResearch,inserted}}
export type SupplierScoutJob=Job;
